// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Selenium;

namespace MoBankUI
{
    internal class Addressconfig
    {
        public void addressconfig(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            datarow.newrow("", "", "ADDRESS CONFIGURATION", "", driver, selenium);
            driver.FindElement(By.Id("DynamicSourceUrl")).Clear();
            driver.FindElement(By.Id("DynamicSourceUrl"))
                  .SendKeys("https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl?ACTION=Start");
            new SelectElement(driver.FindElement(By.Id("Method"))).SelectByText("POST");
            driver.FindElement(By.Id("Url")).Clear();
            driver.FindElement(By.Id("Url")).SendKeys("https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl");
            driver.FindElement(By.Id("LiveScrapeForm_HeaderSelector")).Clear();
            driver.FindElement(By.Id("LiveScrapeForm_HeaderSelector")).SendKeys("#idTableCheckoutSection h2");
            driver.FindElement(By.Id("LiveScrapeForm_SuccessSelector")).Clear();
            driver.FindElement(By.Id("LiveScrapeForm_SuccessSelector")).SendKeys("#GENERALHOWFOUND");
            driver.FindElement(By.Id("LiveScrapeForm_ErrorSelector")).Clear();
            driver.FindElement(By.Id("LiveScrapeForm_ErrorSelector")).SendKeys("#errormessage blockquote");
            driver.FindElement(By.Id("Parameters")).Clear();
            driver.FindElement(By.Id("Parameters"))
                  .SendKeys(
                      "RANDOM=0.346205551018105&SEQUENCE=0&ActCheckoutPhase=INVOICE&ActCheckoutPhase=DELIVER&ActCheckoutPhase=PRELIM&INVOICENAME={{FirstName}}+{{LastName}}&DELIVERNAME={{FirstName}}+{{LastName}}&INVOICEPOSTALCODE={{INVOICEPOSTALCODE}}&DELIVERPOSTALCODE={{INVOICEPOSTALCODE}}&INVOICEADDRESS1={{INVOICEADDRESS1}}&DELIVERADDRESS1={{INVOICEADDRESS1}}&INVOICEADDRESS2={{INVOICEADDRESS2}}&DELIVERADDRESS2={{INVOICEADDRESS2}}&INVOICEADDRESS3={{INVOICEADDRESS3}}&DELIVERADDRESS3={{INVOICEADDRESS3}}&LocationInvoiceCountry={{INVOICECOUNTRY}}&INVOICECOUNTRY={{INVOICECOUNTRY}}&LocationDeliveryCountry={{INVOICECOUNTRY}}&LocationInvoiceRegion=UndefinedRegion&INVOICEADDRESS4={{INVOICEADDRESS4}}&LocationDeliveryRegion=UndefinedRegion&DELIVERADDRESS4={{INVOICEADDRESS4}}&INVOICEPHONE={{INVOICEPHONE}}&DELIVERPHONE={{INVOICEPHONE}}&INVOICEEMAIL={{INVOICEEMAIL}}&DELIVEREMAIL={{INVOICEEMAIL}}&INVOICEEMAIL_CONFIRM={{INVOICEEMAIL}}&DELIVEREMAIL_CONFIRM={{INVOICEEMAIL}}&INVOICEUSERDEFINED={{INVOICEUSERDEFINED}}&ACTION_NEXT.x=87&ACTION_NEXT.y=12");
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");

            #region validations

            string attribute = driver.FindElement(By.Id("DynamicSourceUrl")).GetAttribute("Value");
            string actual = driver.FindElement(By.Id("Url")).GetAttribute("Value");
            string str3 = driver.FindElement(By.Id("LiveScrapeForm_HeaderSelector")).GetAttribute("Value");
            string str4 = driver.FindElement(By.Id("LiveScrapeForm_SuccessSelector")).GetAttribute("Value");
            string str5 = driver.FindElement(By.Id("LiveScrapeForm_ErrorSelector")).GetAttribute("Value");
            string str6 = driver.FindElement(By.Id("Parameters")).GetAttribute("Value");

            if (attribute == "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl?ACTION=Start")
            {
                datarow.newrow("Dynamic Source URL",
                               "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl?ACTION=Start", attribute,
                               "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Dynamic Source URL",
                               "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl?ACTION=Start", attribute,
                               "FAIL", driver, selenium);
            }
            if (actual == "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl")
            {
                datarow.newrow("URL", "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl", actual, "PASS", driver,
                               selenium);
            }
            else
            {
                datarow.newrow("URL", "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl", actual, "FAIL", driver,
                               selenium);
            }
            if (str3 == "#idTableCheckoutSection h2")
            {
                datarow.newrow("Header Selector", "#idTableCheckoutSection h2", str3, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Header Selector", "#idTableCheckoutSection h2", str3, "FAIL", driver, selenium);
            }
            if (str4 == "#GENERALHOWFOUND")
            {
                datarow.newrow("Success Selector", "#GENERALHOWFOUND", str4, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Success Selector", "#GENERALHOWFOUND", str4, "FAIL", driver, selenium);
            }
            if (str5 == "#errormessage blockquote")
            {
                datarow.newrow("Error Selector", "#errormessage blockquote", str5, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Error Selector", "#errormessage blockquote", str5, "FAIL", driver, selenium);
            }
            if (str6 ==
                "RANDOM=0.346205551018105&SEQUENCE=0&ActCheckoutPhase=INVOICE&ActCheckoutPhase=DELIVER&ActCheckoutPhase=PRELIM&INVOICENAME={{FirstName}}+{{LastName}}&DELIVERNAME={{FirstName}}+{{LastName}}&INVOICEPOSTALCODE={{INVOICEPOSTALCODE}}&DELIVERPOSTALCODE={{INVOICEPOSTALCODE}}&INVOICEADDRESS1={{INVOICEADDRESS1}}&DELIVERADDRESS1={{INVOICEADDRESS1}}&INVOICEADDRESS2={{INVOICEADDRESS2}}&DELIVERADDRESS2={{INVOICEADDRESS2}}&INVOICEADDRESS3={{INVOICEADDRESS3}}&DELIVERADDRESS3={{INVOICEADDRESS3}}&LocationInvoiceCountry={{INVOICECOUNTRY}}&INVOICECOUNTRY={{INVOICECOUNTRY}}&LocationDeliveryCountry={{INVOICECOUNTRY}}&LocationInvoiceRegion=UndefinedRegion&INVOICEADDRESS4={{INVOICEADDRESS4}}&LocationDeliveryRegion=UndefinedRegion&DELIVERADDRESS4={{INVOICEADDRESS4}}&INVOICEPHONE={{INVOICEPHONE}}&DELIVERPHONE={{INVOICEPHONE}}&INVOICEEMAIL={{INVOICEEMAIL}}&DELIVEREMAIL={{INVOICEEMAIL}}&INVOICEEMAIL_CONFIRM={{INVOICEEMAIL}}&DELIVEREMAIL_CONFIRM={{INVOICEEMAIL}}&INVOICEUSERDEFINED={{INVOICEUSERDEFINED}}&ACTION_NEXT.x=87&ACTION_NEXT.y=12")
            {
                datarow.newrow("Parameters",
                               "RANDOM=0.346205551018105&SEQUENCE=0&ActCheckoutPhase=INVOICE&ActCheckoutPhase=DELIVER&ActCheckoutPhase=PRELIM&INVOICENAME={{FirstName}}+{{LastName}}&DELIVERNAME={{FirstName}}+{{LastName}}&INVOICEPOSTALCODE={{INVOICEPOSTALCODE}}&DELIVERPOSTALCODE={{INVOICEPOSTALCODE}}&INVOICEADDRESS1={{INVOICEADDRESS1}}&DELIVERADDRESS1={{INVOICEADDRESS1}}&INVOICEADDRESS2={{INVOICEADDRESS2}}&DELIVERADDRESS2={{INVOICEADDRESS2}}&INVOICEADDRESS3={{INVOICEADDRESS3}}&DELIVERADDRESS3={{INVOICEADDRESS3}}&LocationInvoiceCountry={{INVOICECOUNTRY}}&INVOICECOUNTRY={{INVOICECOUNTRY}}&LocationDeliveryCountry={{INVOICECOUNTRY}}&LocationInvoiceRegion=UndefinedRegion&INVOICEADDRESS4={{INVOICEADDRESS4}}&LocationDeliveryRegion=UndefinedRegion&DELIVERADDRESS4={{INVOICEADDRESS4}}&INVOICEPHONE={{INVOICEPHONE}}&DELIVERPHONE={{INVOICEPHONE}}&INVOICEEMAIL={{INVOICEEMAIL}}&DELIVEREMAIL={{INVOICEEMAIL}}&INVOICEEMAIL_CONFIRM={{INVOICEEMAIL}}&DELIVEREMAIL_CONFIRM={{INVOICEEMAIL}}&INVOICEUSERDEFINED={{INVOICEUSERDEFINED}}&ACTION_NEXT.x=87&ACTION_NEXT.y=12",
                               str6, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Parameters",
                               "RANDOM=0.346205551018105&SEQUENCE=0&ActCheckoutPhase=INVOICE&ActCheckoutPhase=DELIVER&ActCheckoutPhase=PRELIM&INVOICENAME={{FirstName}}+{{LastName}}&DELIVERNAME={{FirstName}}+{{LastName}}&INVOICEPOSTALCODE={{INVOICEPOSTALCODE}}&DELIVERPOSTALCODE={{INVOICEPOSTALCODE}}&INVOICEADDRESS1={{INVOICEADDRESS1}}&DELIVERADDRESS1={{INVOICEADDRESS1}}&INVOICEADDRESS2={{INVOICEADDRESS2}}&DELIVERADDRESS2={{INVOICEADDRESS2}}&INVOICEADDRESS3={{INVOICEADDRESS3}}&DELIVERADDRESS3={{INVOICEADDRESS3}}&LocationInvoiceCountry={{INVOICECOUNTRY}}&INVOICECOUNTRY={{INVOICECOUNTRY}}&LocationDeliveryCountry={{INVOICECOUNTRY}}&LocationInvoiceRegion=UndefinedRegion&INVOICEADDRESS4={{INVOICEADDRESS4}}&LocationDeliveryRegion=UndefinedRegion&DELIVERADDRESS4={{INVOICEADDRESS4}}&INVOICEPHONE={{INVOICEPHONE}}&DELIVERPHONE={{INVOICEPHONE}}&INVOICEEMAIL={{INVOICEEMAIL}}&DELIVEREMAIL={{INVOICEEMAIL}}&INVOICEEMAIL_CONFIRM={{INVOICEEMAIL}}&DELIVEREMAIL_CONFIRM={{INVOICEEMAIL}}&INVOICEUSERDEFINED={{INVOICEUSERDEFINED}}&ACTION_NEXT.x=87&ACTION_NEXT.y=12",
                               str6, "FAIL", driver, selenium);
            }

            #endregion

            new AddressElements().elements(driver, selenium, datarow);

            #region Validations

            string str13 = driver.FindElement(By.Id("LiveScrapeForm_Elements_0__Label")).GetAttribute("Value");
            if (str13 == "First Name: *")
            {
                datarow.newrow("First Name", "First Name: *", str13, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("First Name", "First Name: *", str13, "FAIL", driver, selenium);
            }
            string str14 = selenium.GetValue("id=LiveScrapeForm_Elements_0__PropertyPath");
            if (str14 == "FirstName")
            {
                datarow.newrow("FirstName Property", "FirstName", str14, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("FirstName Property", "FirstName", str14, "FAIL", driver, selenium);
            }
            string str15 = driver.FindElement(By.Id("LiveScrapeForm_Elements_1__Label")).GetAttribute("Value");
            if (str15 == "Last Name: *")
            {
                datarow.newrow("LastName", "Last Name: *", str15, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("LastName", "Last Name: *", str15, "FAIL", driver, selenium);
            }
            string str16 = selenium.GetValue("id=LiveScrapeForm_Elements_1__PropertyPath");
            if (str16 == "LastName")
            {
                datarow.newrow("Last Name Property", "LastName", str16, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Last Name Property", "LastName", str16, "FAIL", driver, selenium);
            }
            string str17 = driver.FindElement(By.Id("LiveScrapeForm_Elements_2__Label")).GetAttribute("Value");
            if (str17 == "Post Code: *")
            {
                datarow.newrow("PostCode", "Post Code: *", str17, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("PostCode", "Post Code: *", str17, "FAIL", driver, selenium);
            }
            string str18 = selenium.GetValue("id=LiveScrapeForm_Elements_2__LabelSelector");
            if (str18 == ".actrequired:eq(1)")
            {
                datarow.newrow("PostCode Equation", ".actrequired:eq(1)", str18, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("PostCode Equation", ".actrequired:eq(1)", str18, "FAIL", driver, selenium);
            }
            string str19 = selenium.GetValue("id=LiveScrapeForm_Elements_2__PropertyPath");
            if (str19 == "PostCode")
            {
                datarow.newrow("Postcode Property", "PostCode", str19, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Postcode Property", "PostCode", str19, "FAIL", driver, selenium);
            }
            string str20 = driver.FindElement(By.Id("LiveScrapeForm_Elements_3__LabelSelector")).GetAttribute("Value");
            if (str20 == ".actrequired:eq(2)")
            {
                datarow.newrow("Address Equation", ".actrequired:eq(2)", str20, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Address Equation", ".actrequired:eq(2)", str20, "FAIL", driver, selenium);
            }
            string str21 = driver.FindElement(By.Id("LiveScrapeForm_Elements_3__Label")).GetAttribute("Value");
            if (str21 == "Address Line 1: *")
            {
                datarow.newrow("Address", "Address Line 1: *", str21, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Address", "Address Line 1: *", str21, "FAIL", driver, selenium);
            }
            string text = selenium.GetText("id=LiveScrapeForm_Elements_3__PropertyPath");
            if (text == "Address1")
            {
                datarow.newrow("Address Property", "Address1", text, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Address Property", "Address1", text, "PASS", driver, selenium);
            }
            string str23 = driver.FindElement(By.Id("LiveScrapeForm_Elements_4__LabelSelector")).GetAttribute("Value");
            if (str23 == "#idBothAddressesTable tr:eq(5) td:eq(0)")
            {
                datarow.newrow("Address Equation2", "#idBothAddressesTable tr:eq(5) td:eq(0)", str23, "PASS", driver,
                               selenium);
            }
            else
            {
                datarow.newrow("Address Equation2", "#idBothAddressesTable tr:eq(5) td:eq(0)", str23, "FAIL", driver,
                               selenium);
            }
            string str24 = driver.FindElement(By.Id("LiveScrapeForm_Elements_4__Label")).GetAttribute("Value");
            if (str24 == "Address Line 2:")
            {
                datarow.newrow("Address2", "Address Line 2:", str24, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Address2", "Address Line 2:", str24, "FAIL", driver, selenium);
            }
            string str25 = selenium.GetValue("id=LiveScrapeForm_Elements_4__PropertyPath");
            if (str25 == "Address2")
            {
                datarow.newrow("Address2Property", "Address2", str25, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Address2Property", "Address2", str25, "FAIL", driver, selenium);
            }
            string str26 = driver.FindElement(By.Id("LiveScrapeForm_Elements_5__LabelSelector")).GetAttribute("Value");
            if (str26 == ".actrequired:eq(3)")
            {
                datarow.newrow("City Equation", ".actrequired:eq(3)", str26, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("City Equation", ".actrequired:eq(3)", str26, "FAIL", driver, selenium);
            }
            string str27 = driver.FindElement(By.Id("LiveScrapeForm_Elements_5__Label")).GetAttribute("Value");
            if (str27 == "City/Town: *")
            {
                datarow.newrow("Billing City", "City/Town: *", str27, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Billing City", "City/Town: *", str27, "FAIL", driver, selenium);
            }
            string str28 = selenium.GetValue("id=LiveScrapeForm_Elements_5__PropertyPath");
            if (str28 == "BillingCity")
            {
                datarow.newrow("Billing City Property", "BillingCity", str28, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Billing City Property", "BillingCity", str28, "FAIL", driver, selenium);
            }
            string str29 = driver.FindElement(By.Id("LiveScrapeForm_Elements_6__LabelSelector")).GetAttribute("Value");
            if (str29 == "#idBothAddressesTable tr:eq(7) td:eq(0)")
            {
                datarow.newrow("Country Eqaution", "#idBothAddressesTable tr:eq(7) td:eq(0)", str29, "PASS", driver,
                               selenium);
            }
            else
            {
                datarow.newrow("Country Eqaution", "#idBothAddressesTable tr:eq(7) td:eq(0)", str29, "FAIL", driver,
                               selenium);
            }
            string str30 = driver.FindElement(By.Id("LiveScrapeForm_Elements_6__Label")).GetAttribute("Value");
            if (str30 == "Country: *")
            {
                datarow.newrow("Country", "Country: *", str30, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Country", "Country: *", str30, "FAIL", driver, selenium);
            }
            string str31 =
                driver.FindElement(By.Id("LiveScrapeForm_Elements_6__KeysValuesSelector")).GetAttribute("Value");
            if (str31 == "#lstInvoiceCountry option")
            {
                datarow.newrow("Country Option", "#lstInvoiceCountry option", str31, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Country Option", "#lstInvoiceCountry option", str31, "FAIL", driver, selenium);
            }
            string str32 = selenium.GetValue("id=LiveScrapeForm_Elements_6__PropertyPath");
            if (str32 == "Country")
            {
                datarow.newrow("Country Property", "Country", str32, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Country Property", "Country", str32, "FAIL", driver, selenium);
            }
            if (driver.FindElement(By.Id("LiveScrapeForm_Elements_7__LabelSelector")).GetAttribute("Value") ==
                "#idBothAddressesTable tr:eq(8) td:eq(0)")
            {
                datarow.newrow("County Equation", "#idBothAddressesTable tr:eq(8) td:eq(0)", str29, "PASS", driver,
                               selenium);
            }
            else
            {
                datarow.newrow("County Equation", "#idBothAddressesTable tr:eq(8) td:eq(0)", str29, "FAIL", driver,
                               selenium);
            }
            string str34 = driver.FindElement(By.Id("LiveScrapeForm_Elements_7__Label")).GetAttribute("Value");
            if (str34 == "County:")
            {
                datarow.newrow("County", "County:", str34, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("County", "County:", str34, "FAIL", driver, selenium);
            }
            string str35 = selenium.GetValue("id=LiveScrapeForm_Elements_7__PropertyPath");
            if (str35 == "County")
            {
                datarow.newrow("County Property", "County", str35, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("County Property", "County", str35, "PASS", driver, selenium);
            }
            string str36 = selenium.GetValue("id=LiveScrapeForm_Elements_8__LabelSelector");
            if (str36 == "#idBothAddressesTable tr:eq(9) td:eq(0)")
            {
                datarow.newrow("Phone Equation", "#idBothAddressesTable tr:eq(9) td:eq(0)", str36, "PASS", driver,
                               selenium);
            }
            else
            {
                datarow.newrow("Phone Equation", "#idBothAddressesTable tr:eq(9) td:eq(0)", str36, "FAIL", driver,
                               selenium);
            }
            string str37 = driver.FindElement(By.Id("LiveScrapeForm_Elements_8__Label")).GetAttribute("Value");
            if (str37 == "Phone Number:")
            {
                datarow.newrow("Phone Number", "Phone Number:", str37, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Phone Number", "Phone Number:", str37, "FAIL", driver, selenium);
            }
            string str38 = selenium.GetValue("id=LiveScrapeForm_Elements_8__PropertyPath");
            if (str38 == "Phone")
            {
                datarow.newrow("Phone Property", "Phone", str38, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Phone Property", "Phone", str38, "FAIL", driver, selenium);
            }
            string str39 = selenium.GetValue("id=LiveScrapeForm_Elements_9__LabelSelector");
            if (str39 == "#idINVOICEEMAILlabel")
            {
                datarow.newrow("Email Equation", "#idINVOICEEMAILlabel", str39, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Email Equation", "#idINVOICEEMAILlabel", str39, "FAIL", driver, selenium);
            }
            string str40 = selenium.GetValue("LiveScrapeForm_Elements_9__Label");
            if (str40 == "Email Address: *")
            {
                datarow.newrow("Email", "Email Address: *", str40, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Email", "Email Address: *", str40, "FAIL", driver, selenium);
            }
            string str41 = selenium.GetValue("id=LiveScrapeForm_Elements_9__PropertyPath");
            if (str41 == "Email")
            {
                datarow.newrow("Email Property", "Email", str41, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Email Property", "Email", str41, "FAIL", driver, selenium);
            }

            #endregion

            new Delivery().delivery(driver, selenium, datarow);
        }
    }
}