// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using System.Text.RegularExpressions;
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;

namespace MoBankUI.MoPay
{
    public class MopayBackup : Driverdefining
    {
        private readonly Datarow _datarow = new Datarow();
        private GeneralLibrary _generalLibrary;

        public void Dsecure(IWebDriver driver)
        {
            if (IsElementPresent(driver, By.TagName("iframe")))
            {
                var frameElement = driver.FindElement(By.TagName("iframe"));
                driver.SwitchTo().Frame(frameElement);
                driver.FindElement(By.CssSelector("input[type=\"submit\"]")).Click();
                Thread.Sleep(0x1388);
                driver.SwitchTo().Alert().Accept();

                var location = driver.Url;
                if (location.Contains("3DSecureState=Success"))
                {
                    _datarow.Newrow("3D secure", location, "3DSecureState=Success", "PASS", driver);
                    driver.FindElement(By.LinkText("start again")).Click();
                }
                else if (location.Contains("State=Declined"))
                {
                    _datarow.Newrow("3D secure", location, "3D secure Declined", "FAIL", driver);
                    driver.FindElement(By.LinkText("start again")).Click();
                }
            }
            else
            {
                var actual = driver.Url;
                _datarow.Newrow("Checkout", "Server Error", actual, "FAIL", driver);
                new Screenshot().Screenshotfailed(driver);
                driver.Navigate().GoToUrl("http://devpaytest.mobankdev.com/");
            }
        }

        public void MoPay(IWebDriver driver)
        {
            _generalLibrary = new GeneralLibrary();
            var excelData = _generalLibrary.GetExcelData(@"C:\\Input Data\CardDetails.xls", "CardDetails");
            var set2 = _generalLibrary.GetExcelData(@"C:\\Input Data\CardDetails.xls", "Account");
            _datarow.Col();
            var table = excelData.Tables[0];
            var table2 = set2.Tables[0];
            var count = table2.Rows.Count;
            try
            {
                for (var i = 0; i < count; i++)
                {
                    var locator = table2.Rows[i]["Account"].ToString();
                    var str2 = table2.Rows[i]["Type"].ToString();
                    var str3 = table2.Rows[i]["E-mail"].ToString();
                    var str4 = table2.Rows[i]["FormData"].ToString();
                    var str5 = table2.Rows[i]["FormValue"].ToString();
                    var str6 = table2.Rows[i]["CookieData"].ToString();
                    var str7 = table2.Rows[i]["CookieValue"].ToString();
                    driver.Navigate().GoToUrl("http://devpaytest.mobankdev.com/");
                    driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(15.0));
                    driver.FindElement(By.XPath("//div[@id='ReferenceControl']/div/input"));
                    driver.FindElement(By.XPath(locator)).Click();
                    driver.FindElement(By.Id(locator)).Click();
                    driver.FindElement(By.Id(str2)).Click();
                    driver.FindElement(By.XPath("//div[@id='ReferenceControl']/div/input"))
                        .GetAttribute("Reference");
                    driver.FindElement(By.XPath("//div[@id='TotalAmountControl']/div/input")).GetAttribute("Amt");
                    driver.FindElement(By.XPath("//div[@id='CurrencyCodeControl']/div/select")).GetAttribute("Cur");
                    var input = table.Rows[0]["FirstName"].ToString();
                    var str12 = table.Rows[0]["LastName"].ToString();
                    Assert.AreEqual("The MoShop Sale",
                                    driver.FindElement(By.XPath("//div[@id='DescriptionControl']/div/textarea")).Text);
                    var screenshot = new Screenshot();
                    driver.FindElement(By.XPath("//div[@id='FirstNameControl']/div/input")).Clear();
                    driver.FindElement(By.XPath("//div[@id='FirstNameControl']/div/input")).SendKeys(input);
                    driver.FindElement(By.XPath("//div[@id='LastNameControl']/div/input")).Clear();
                    driver.FindElement(By.XPath("//div[@id='LastNameControl']/div/input")).SendKeys(str12);
                    driver.FindElement(By.XPath("//div[@id='EmailControl']/div/input")).Clear();
                    driver.FindElement(By.XPath("//div[@id='EmailControl']/div/input")).SendKeys(str3);
                    driver.FindElement(By.CssSelector("button")).Click();
                    driver.FindElement(By.Name("FormData[1].Key")).SendKeys(str4);
                    driver.FindElement(By.Name("FormData[1].Value")).SendKeys(str5);
                    driver.FindElement(By.CssSelector("#CookieData > button")).Click();
                    driver.FindElement(By.Name("CookieData[1].Key")).SendKeys(str6);
                    driver.FindElement(By.Name("CookieData[1].Value")).SendKeys(str7);
                    driver.FindElement(By.CssSelector("input[type=\"submit\"]")).Click();
                    try
                    {
                    }
                    catch (Exception exception)
                    {
                        Console.Write(exception);
                    }
                    var num3 = table.Rows.Count;
                    for (var j = 0; j < num3; j++)
                    {
                        var str13 = table.Rows[j]["Card Number"].ToString();
                        var str14 = table.Rows[j]["Security Code"].ToString();
                        var expected = table.Rows[j]["CardType"].ToString();
                        var str16 = table.Rows[j]["Name on Card"].ToString();
                        var optionLocator = table.Rows[j]["ExpiryMonth"].ToString();
                        var str18 = table.Rows[j]["Expiry Year"].ToString();
                        var str19 = table.Rows[j]["Phone Number"].ToString();
                        var str20 = table.Rows[j]["Address"].ToString();
                        var str21 = table.Rows[j]["City"].ToString();
                        var str22 = table.Rows[j]["Post Code"].ToString();
                        var str23 = table.Rows[j]["County"].ToString();
                        var str24 = table.Rows[j]["Country"].ToString();
                        driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(60.0));
                        driver.FindElement(By.XPath("//div[@id='Card.NameControl']/input"));
                        Assert.AreEqual("Secure Payment Page", driver.Title);
                        driver.FindElement(By.XPath("//*[@id='Card_Number']")).SendKeys(str13);
                        driver.FindElement(By.Id("//*[@id='Card_SecurityCode']")).SendKeys(str14);
                        new SelectElement(driver.FindElement(By.Id("Card_Type"))).SelectByText("Visa Debit");
                        new SelectElement(driver.FindElement(By.Id("Card_ExpiryDate_Month"))).SelectByText(optionLocator);
                        new SelectElement(driver.FindElement(By.Id("Card_ExpiryDate_Year"))).SelectByText(str18);
                        driver.FindElement(By.XPath("//div[@id='Card.NameControl']/input")).SendKeys(str16);
                        switch (str2)
                        {
                            case "id=actionPay":
                                driver.FindElement(By.Id("BillingContact_Phone_Number")).SendKeys(str19);
                                driver.FindElement(By.Id("BillingContact_Address_Line1")).SendKeys(str20);
                                driver.FindElement(By.XPath("//div[@id='BillingContact.Address.Line2Control']/input"))
                                      .SendKeys("s");
                                driver.FindElement(By.Id("BillingContact_Address_Postcode")).SendKeys(str22);
                                driver.FindElement(By.XPath("//div[@id='BillingContact.Address.TownControl']/input"))
                                      .SendKeys(str21);
                                driver.FindElement(By.Id("BillingContact_Address_County")).SendKeys(str23);
                                new SelectElement(
                                    driver.FindElement(
                                        By.XPath("//div[@id='BillingContact.Address.CountryControl']/div/div/select")))
                                    .SelectByText(str24);

                                break;

                            case "id=actionToken":
                                driver.FindElement(By.Id("Contact_Phone_Number")).SendKeys(str19);
                                driver.FindElement(By.Id("Contact_Address_Line1")).SendKeys(str20);
                                driver.FindElement(By.XPath("//div[@id='Contact.Address.Line2Control']/input"))
                                      .SendKeys("s");
                                driver.FindElement(By.Id("Contact_Address_Postcode")).SendKeys(str22);
                                driver.FindElement(By.XPath("//div[@id='Contact.Address.TownControl']/input"))
                                      .SendKeys(str21);
                                driver.FindElement(By.Id("Contact_Address_County")).SendKeys(str23);
                                new SelectElement(
                                    driver.FindElement(
                                        By.XPath("//div[@id='Contact.Address.CountryControl']/div/div/select")))
                                    .SelectByText(str24);
                                break;
                        }
                        driver.FindElement(By.Name("PostAction[Complete]")).Click();

                        Thread.Sleep(0x1388);
                        if (Regex.IsMatch(str13, "^[0-9'']"))
                        {
                            _datarow.Newrow("Card Number", str13, str13, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("Number required") ||
                                 driver.PageSource.Contains("Number invalid"))
                        {
                            _datarow.Newrow("Card Number", str13, "Number Invalid", "PASS", driver);
                        }
                        else
                        {
                            _datarow.Newrow("Card Number", str13, "No Error Message Displayed", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        _datarow.Newrow("Card Type", expected, expected, "PASS", driver);
                        var regex = new Regex("^[0-9]{3}$");
                        if (regex.IsMatch(str14))
                        {
                            _datarow.Newrow("Security Code", str14, "Valid 3 Digits", "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("Security code required") ||
                                 driver.PageSource.Contains("Security code invalid"))
                        {
                            _datarow.Newrow("Security Code", str14, "Security code required", "PASS", driver
                                );
                        }
                        else
                        {
                            _datarow.Newrow("Security Code", str14, "No Error Message Displayed", "FAIL", driver
                                );
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(str16, "^[a-zA-Z'']"))
                        {
                            _datarow.Newrow("Name on Card", str16, str16, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("Name required"))
                        {
                            _datarow.Newrow("Name on Card", str16, "Name Required", "PASS", driver);
                        }
                        else
                        {
                            _datarow.Newrow("Name on Card", str16, "No Error Message Displayed", "PASS", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(input, "^[a-zA-Z'']"))
                        {
                            _datarow.Newrow("First Name", input, input, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("The First Name field is required."))
                        {
                            _datarow.Newrow("First Name", input, "The First Name field is required.", "PASS", driver
                                );
                        }
                        else
                        {
                            _datarow.Newrow("First Name", input, "No Error Message Displayed", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(str12, "^[a-zA-Z'']"))
                        {
                            _datarow.Newrow("Last Name", str12, str12, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("The Last Name field is required."))
                        {
                            _datarow.Newrow("Last Name", str12, "The Last Name field is required.", "PASS", driver
                                );
                        }
                        else
                        {
                            _datarow.Newrow("Last Name", str12, "No Error message Displayed", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(str20, "^[a-zA-Z0-9'']"))
                        {
                            _datarow.Newrow("Address", str20, str20, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("The Address field is required"))
                        {
                            _datarow.Newrow("Address", str20, "The Address field is required", "PASS", driver);
                        }
                        else
                        {
                            _datarow.Newrow("Address", str20, "No Error message Displayed", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(str22, "^[a-zA-Z0-9'']"))
                        {
                            _datarow.Newrow("Post Code", str22, str22, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("The Postcode field is required"))
                        {
                            _datarow.Newrow("Post Code", str22, "The Postcode field is required.", "PASS", driver
                                );
                        }
                        else
                        {
                            _datarow.Newrow("Post Code", str22, "No Error Message Displayed", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        if (Regex.IsMatch(str24, "^[a-zA-Z'']"))
                        {
                            _datarow.Newrow("Country", str24, str24, "PASS", driver);
                        }
                        else if (driver.PageSource.Contains("The Country field is required."))
                        {
                            _datarow.Newrow("Country", str24, "The Country field is required.", "PASS", driver);
                        }
                        else
                        {
                            _datarow.Newrow("Country", str24, "No Error Message", "FAIL", driver);
                            screenshot.Screenshotfailed(driver);
                        }
                        var title = driver.Title;
                        if (title == "Secure Payment Page") continue;
                        if (title == "Redirect to External")
                        {
                            Dsecure(driver);
                            break;
                        }
                        if (driver.PageSource.Contains("Checkout Accepted"))
                        {
                            Normaltransaction(driver);
                            break;
                        }
                        if (!driver.PageSource.Contains("Checkout Declined") &&
                            !driver.PageSource.Contains("Checkout Error")) continue;
                        _datarow.Newrow("Checkout", "Checkout Declined", "Checkout Declined", "PASS", driver
                            );
                        driver.FindElement(By.LinkText("start again")).Click();
                        break;
                    }
                }
            }
            catch (Exception exception2)
            {
                Console.Write(exception2);
                var actual = exception2.ToString();
                var screenshot2 = new Screenshot();
                _datarow.Newrow("Checkout", "Server Error", actual, "FAIL", driver);
                screenshot2.Screenshotfailed(driver);
            }
            finally
            {
                new Screenshot().Screenshotnotifications(driver);
                _datarow.excelsave("MoPayReport", driver, "teja.vellanki@mobankgroup.com");
                driver.Quit();
            }
        }

        public void Normaltransaction(IWebDriver driver)
        {
            var location = driver.Url;
            if (location.Contains("State=Accepted"))
            {
                _datarow.Newrow("Transaction", location, "State=Accepted", "PASS", driver);
                driver.FindElement(By.LinkText("start again")).Click();
            }
            else if (location.Contains("State=Declined"))
            {
                _datarow.Newrow("Transaction", location, "Transaction Declined", "FAIL", driver);
                driver.FindElement(By.LinkText("start again")).Click();
            }
            else
            {
                var actual = driver.Url;
                _datarow.Newrow("Checkout", "Server Error", actual, "FAIL", driver);
                new Screenshot().Screenshotfailed(driver);
                driver.Navigate().GoToUrl("http://devpaytest.mobankdev.com/");
            }
        }
    }
}