// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using System.Data;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Selenium;

namespace MoBankUI
{
    internal class Notificationtab
    {
        private readonly Screenshot screenshot = new Screenshot();
        private GeneralLibrary genaralLibrary;

        public void Notifications(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            string str10;
            genaralLibrary = new GeneralLibrary();
            DataTable table =
                genaralLibrary.GetExcelData(@"C:\Selenium\Input Data\CardDetails.xls", "AccountCreation").Tables[0];
            int count = table.Rows.Count;
            string expected = table.Rows[0]["PayNotificationsCallBack"].ToString();
            string str2 = table.Rows[0]["TokenNotificationscallback"].ToString();
            string str3 = table.Rows[0]["SuccesfullTransactions"].ToString();
            string str4 = table.Rows[0]["DailyEmail"].ToString();
            string str5 = table.Rows[0]["WeeklyEmail"].ToString();
            string str6 = table.Rows[0]["MonthlyEmail"].ToString();
            string attribute = driver.FindElement(By.Id("SendSuccessfulTransactionReports")).GetAttribute("value");
            if (attribute == "true")
            {
                datarow.newrow("Successful Transaction Option", "on", attribute, "PASS", driver, selenium);
                driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).Clear();
                driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).SendKeys(str3);
            }
            else
            {
                driver.FindElement(By.Id("SendSuccessfulTransactionReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                if (driver.FindElement(By.Id("SendSuccessfulTransactionReports")).GetAttribute("value") == "true")
                {
                    datarow.newrow("Successful Transaction Option", "on", attribute, "PASS", driver, selenium);
                    driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).Clear();
                    driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).SendKeys(str3);
                }
                else
                {
                    datarow.newrow("Successful Transaction Option", "on", attribute, "FAIL", driver, selenium);
                    screenshot.screenshotfailed(driver, selenium);
                }
            }
            string actual = driver.FindElement(By.Id("SendDailyReports")).GetAttribute("value");
            if (actual == "true")
            {
                datarow.newrow("Daily Email", "on", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("DailyReportEmail")).Clear();
                driver.FindElement(By.Id("DailyReportEmail")).SendKeys(str4);
            }
            else
            {
                datarow.newrow("Daily Email", "off", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("SendDailyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                str10 = driver.FindElement(By.Id("SendDailyReports")).GetAttribute("value");
                if (str10 == "true")
                {
                    datarow.newrow("Daily Email", "ON", str10, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Daily Email", "ON", str10, "FAIL", driver, selenium);
                }
            }
            if (driver.FindElement(By.Id("SendWeeklyReports")).GetAttribute("value") == "true")
            {
                datarow.newrow("Weekly Email", "on", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("WeeklyReportEmail")).Clear();
                driver.FindElement(By.Id("WeeklyReportEmail")).SendKeys(str5);
            }
            else
            {
                datarow.newrow("Weekly Email", "off", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("SendWeeklyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                str10 = driver.FindElement(By.Id("SendWeeklyReports")).GetAttribute("value");
                if (str10 == "true")
                {
                    datarow.newrow("Weekly Email", "ON", str10, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Weekly Email", "ON", str10, "FAIL", driver, selenium);
                }
            }
            if (driver.FindElement(By.Id("SendMonthlyReports")).GetAttribute("value") == "true")
            {
                datarow.newrow("Weekly Email", "on", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("MonthlyReportEmail")).Clear();
                driver.FindElement(By.Id("MonthlyReportEmail")).SendKeys(str5);
            }
            else
            {
                datarow.newrow("Monthly Email", "off", actual, "PASS", driver, selenium);
                driver.FindElement(By.Id("SendMonthlyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                str10 = driver.FindElement(By.Id("SendMonthlyReports")).GetAttribute("value");
                if (str10 == "true")
                {
                    datarow.newrow("Monthly Email", "ON", str10, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Monthly Email", "ON", str10, "FAIL", driver, selenium);
                }
            }
            new SelectElement(driver.FindElement(By.Id("Notifications_1__Event"))).SelectByText("Pay");
            driver.FindElement(By.Id("Notifications_0__Url")).Clear();
            driver.FindElement(By.Id("Notifications_0__Url")).SendKeys(expected);
            new SelectElement(driver.FindElement(By.Id("Notifications_0__Event"))).SelectByText("Token");
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");
            driver.FindElement(By.Id("Notifications_1__Url")).Clear();
            driver.FindElement(By.Id("Notifications_1__Url")).SendKeys(str2);
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");
            string str13 = driver.FindElement(By.Id("Notifications_1__Url")).GetAttribute("Value");
            string str14 = driver.FindElement(By.Id("Notifications_2__Url")).GetAttribute("Value");
            if (str13 == expected)
            {
                datarow.newrow("Pay Call Back URL", expected, str13, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Pay Call Back URL", expected, str13, "FAIL", driver, selenium);
            }
            if (str2 == str14)
            {
                datarow.newrow("Token Call Back URL", str2, str14, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Token Call Back URL", str2, str14, "FAIL", driver, selenium);
            }
        }
    }
}