// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;

namespace MoBankUI.MoPay
{
    internal class Notificationtab : Driverdefining
    {
        private readonly Screenshot _screenshot = new Screenshot();
        private GeneralLibrary _genaralLibrary;

        public void Notifications(IWebDriver driver, Datarow datarow)
        {
            string str10;
            _genaralLibrary = new GeneralLibrary();
            var table =
                _genaralLibrary.GetExcelData(@"C:\\Input Data\CardDetails.xls", "AccountCreation").Tables[0];
            var expected = table.Rows[0]["PayNotificationsCallBack"].ToString();
            var str2 = table.Rows[0]["TokenNotificationscallback"].ToString();
            var str3 = table.Rows[0]["SuccesfullTransactions"].ToString();
            var str4 = table.Rows[0]["DailyEmail"].ToString();
            var str5 = table.Rows[0]["WeeklyEmail"].ToString();
            var attribute = driver.FindElement(By.Id("SendSuccessfulTransactionReports")).GetAttribute("value");
            if (attribute == "true")
            {
                datarow.Newrow("Successful Transaction Option", "on", attribute, "PASS", driver);
                driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).Clear();
                driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).SendKeys(str3);
            }
            else
            {
                driver.FindElement(By.Id("SendSuccessfulTransactionReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();

                if (driver.FindElement(By.Id("SendSuccessfulTransactionReports")).GetAttribute("value") == "true")
                {
                    datarow.Newrow("Successful Transaction Option", "on", attribute, "PASS", driver);
                    driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).Clear();
                    driver.FindElement(By.Id("SuccessfulTransactionReportEmail")).SendKeys(str3);
                }
                else
                {
                    datarow.Newrow("Successful Transaction Option", "on", attribute, "FAIL", driver);
                    _screenshot.Screenshotfailed(driver);
                }
            }
            var actual = driver.FindElement(By.Id("SendDailyReports")).GetAttribute("value");
            if (actual == "true")
            {
                datarow.Newrow("Daily Email", "on", actual, "PASS", driver);
                driver.FindElement(By.Id("DailyReportEmail")).Clear();
                driver.FindElement(By.Id("DailyReportEmail")).SendKeys(str4);
            }
            else
            {
                datarow.Newrow("Daily Email", "off", actual, "PASS", driver);
                driver.FindElement(By.Id("SendDailyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();

                str10 = driver.FindElement(By.Id("SendDailyReports")).GetAttribute("value");
                datarow.Newrow("Daily Email", "ON", str10, str10 == "true" ? "PASS" : "FAIL", driver);
            }
            if (driver.FindElement(By.Id("SendWeeklyReports")).GetAttribute("value") == "true")
            {
                datarow.Newrow("Weekly Email", "on", actual, "PASS", driver);
                driver.FindElement(By.Id("WeeklyReportEmail")).Clear();
                driver.FindElement(By.Id("WeeklyReportEmail")).SendKeys(str5);
            }
            else
            {
                datarow.Newrow("Weekly Email", "off", actual, "PASS", driver);
                driver.FindElement(By.Id("SendWeeklyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();

                str10 = driver.FindElement(By.Id("SendWeeklyReports")).GetAttribute("value");
                datarow.Newrow("Weekly Email", "ON", str10, str10 == "true" ? "PASS" : "FAIL", driver);
            }
            if (driver.FindElement(By.Id("SendMonthlyReports")).GetAttribute("value") == "true")
            {
                datarow.Newrow("Weekly Email", "on", actual, "PASS", driver);
                driver.FindElement(By.Id("MonthlyReportEmail")).Clear();
                driver.FindElement(By.Id("MonthlyReportEmail")).SendKeys(str5);
            }
            else
            {
                datarow.Newrow("Monthly Email", "off", actual, "PASS", driver);
                driver.FindElement(By.Id("SendMonthlyReports")).Click();
                driver.FindElement(By.CssSelector("input.button")).Click();

                str10 = driver.FindElement(By.Id("SendMonthlyReports")).GetAttribute("value");
                datarow.Newrow("Monthly Email", "ON", str10, str10 == "true" ? "PASS" : "FAIL", driver);
            }
            new SelectElement(driver.FindElement(By.Id("Notifications_1__Event"))).SelectByText("Pay");
            driver.FindElement(By.Id("Notifications_0__Url")).Clear();
            driver.FindElement(By.Id("Notifications_0__Url")).SendKeys(expected);
            new SelectElement(driver.FindElement(By.Id("Notifications_0__Event"))).SelectByText("Token");
            driver.FindElement(By.CssSelector("input.button")).Click();

            driver.FindElement(By.Id("Notifications_1__Url")).Clear();
            driver.FindElement(By.Id("Notifications_1__Url")).SendKeys(str2);
            driver.FindElement(By.CssSelector("input.button")).Click();

            var str13 = driver.FindElement(By.Id("Notifications_1__Url")).GetAttribute("Value");
            var str14 = driver.FindElement(By.Id("Notifications_2__Url")).GetAttribute("Value");
            datarow.Newrow("Pay Call Back URL", expected, str13, str13 == expected ? "PASS" : "FAIL", driver);
            datarow.Newrow("Token Call Back URL", str2, str14, str2 == str14 ? "PASS" : "FAIL", driver);
        }
    }
}