// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using System.Data;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Selenium;

namespace MoBankUI
{
    public class Paymentprovider
    {
        private readonly Screenshot screenshot = new Screenshot();
        private GeneralLibrary genaralLibrary;

        public void provider(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            genaralLibrary = new GeneralLibrary();
            DataTable table =
                genaralLibrary.GetExcelData(@"C:\Selenium\Input Data\CardDetails.xls", "AccountCreation").Tables[0];
            int count = table.Rows.Count;
            string str = table.Rows[0]["AccountName"].ToString();
            string text = table.Rows[0]["Provider"].ToString();
            string str3 = table.Rows[0]["ProviderIdentifier"].ToString();
            string str4 = table.Rows[0]["ProviderUserName"].ToString();
            string str5 = table.Rows[0]["Implementation"].ToString();
            string str6 = table.Rows[0]["Allow3DSecure"].ToString();
            new SelectElement(driver.FindElement(By.Id("PayProvider_Id"))).SelectByText(text);
            string attribute = driver.FindElement(By.Id("PayProvider_Id")).GetAttribute("Value");
            if (text == attribute)
            {
                datarow.newrow("Provider", text, attribute, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Provider", text, attribute, "FAIL", driver, selenium);
            }
            new Paymentprovidertypes().paymenttypes(driver, selenium, datarow);
            driver.FindElement(By.LinkText("…")).Click();
            selenium.WaitForPageToLoad("30000");
            new SelectElement(driver.FindElement(By.Id("Implementation"))).SelectByText(str5);
            string actual = driver.FindElement(By.Id("Allow3DSecure")).GetAttribute("value");
            if (actual == "off")
            {
                datarow.newrow("3Dsecure", "OFF", actual, "PASS", driver, selenium);
                if (selenium.IsElementPresent("Allow3DSecure"))
                {
                    driver.FindElement(By.Id("Allow3DSecure")).Click();
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                }
            }
            if (driver.FindElement(By.Id("Allow3DSecure")).GetAttribute("value") == "true")
            {
                datarow.newrow("3Dsecure", "ON", actual, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("3Dsecure", "OFF", actual, "FAIL", driver, selenium);
                screenshot.screenshotfailed(driver, selenium);
            }
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");
            string expected = driver.FindElement(By.Id("Implementation")).GetAttribute("Value");
            if (expected == str5)
            {
                datarow.newrow("Implementation", expected, str5, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Implementation", expected, str5, "FAIL", driver, selenium);
            }
            selenium.Click("//html/body/div/div[2]/div/div/div/form/div[5]/div/div/table/tbody/tr/th[2]/a");
            selenium.WaitForPageToLoad("30000");
            string str11 = driver.FindElement(By.Id("Name")).GetAttribute("value");
            if (str11 == "Visa Debit")
            {
                datarow.newrow("Card Type -Visa Debit", "Visa Debit", str11, "PASS", driver, selenium);
                new VisaDebit().Visadebit(driver, selenium, datarow);
            }
            selenium.GoBack();
            selenium.WaitForPageToLoad("30000");
            driver.FindElement(By.XPath("//div[@id='CardTypesControl']/div/table/tbody/tr[2]/th[2]/a")).Click();
            selenium.WaitForPageToLoad("30000");
            if (driver.FindElement(By.Id("Name")).GetAttribute("value") == "Mastercard")
            {
                datarow.newrow("Card Type -Mastercard", "Mastercard", str11, "PASS", driver, selenium);
                new Mastercard().mastercard(driver, selenium, datarow);
            }
            selenium.MouseOver("//html/body/div/div/div/div[2]/ul/li/a");
            selenium.GoBack();
            Thread.Sleep(0x1388);
            selenium.GoBack();
            Thread.Sleep(0x2710);
            selenium.GoBack();
            driver.FindElement(By.LinkText("Payment Provider")).Click();
            Thread.Sleep(0x1388);
            if (selenium.IsElementPresent("CardTypes_0____selector"))
            {
                string str13 = driver.FindElement(By.Id("CardTypes_0____selector")).GetAttribute("value");
                if (str13 == "false")
                {
                    datarow.newrow("Card1", "off", str13, "PASS", driver, selenium);
                    driver.FindElement(By.Id("CardTypes_0____selector")).Click();
                }
            }
            if (selenium.IsElementPresent("CardTypes_1____selector"))
            {
                string str14 = driver.FindElement(By.Id("CardTypes_1____selector")).GetAttribute("value");
                if (str14 == "false")
                {
                    datarow.newrow("Card2", "off", str14, "PASS", driver, selenium);
                    driver.FindElement(By.Id("CardTypes_1____selector")).Click();
                }
            }
            if (selenium.IsElementPresent("CardTypes_2____selector"))
            {
                string str15 = driver.FindElement(By.Id("CardTypes_2____selector")).GetAttribute("value");
                if (str15 == "true")
                {
                    datarow.newrow("Card3", "on", str15, "PASS", driver, selenium);
                    driver.FindElement(By.Id("CardTypes_2____selector")).Click();
                }
            }
            if (selenium.IsElementPresent("CardTypes_3____selector"))
            {
                string str16 = driver.FindElement(By.Id("CardTypes_3____selector")).GetAttribute("value");
                if (str16 == "true")
                {
                    datarow.newrow("Card4", "on", str16, "PASS", driver, selenium);
                    driver.FindElement(By.Id("CardTypes_3____selector")).Click();
                }
            }
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");
            if (selenium.IsElementPresent("CardTypes_0____selector"))
            {
                string str17 = driver.FindElement(By.Id("CardTypes_0____selector")).GetAttribute("value");
                if (str17 == "false")
                {
                    datarow.newrow("Card1", "off", str17, "FAIL", driver, selenium);
                    screenshot.screenshotfailed(driver, selenium);
                }
                else
                {
                    datarow.newrow("Card1", "on", str17, "PASS", driver, selenium);
                }
            }
            if (selenium.IsElementPresent("CardTypes_1____selector"))
            {
                string str18 = driver.FindElement(By.Id("CardTypes_1____selector")).GetAttribute("value");
                if (str18 == "false")
                {
                    datarow.newrow("Card2", "off", str18, "FAIL", driver, selenium);
                    screenshot.screenshotfailed(driver, selenium);
                }
                else
                {
                    datarow.newrow("Card2", "on", str18, "PASS", driver, selenium);
                }
            }
            if (selenium.IsElementPresent("CardTypes_2____selector"))
            {
                string str19 = driver.FindElement(By.Id("CardTypes_2____selector")).GetAttribute("value");
                if (str19 == "true")
                {
                    datarow.newrow("Card3", "on", str19, "FAIL", driver, selenium);
                    screenshot.screenshotfailed(driver, selenium);
                }
                else
                {
                    datarow.newrow("Card3", "off", str19, "PASS", driver, selenium);
                }
            }
        }
    }
}