// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using OpenQA.Selenium;

namespace MoBankUI
{
    internal class VisaDebit
    {
        public void Visadebit(IWebDriver driver, datarow datarow)
        {
            string attribute = driver.FindElement(By.Id("NumberPattern")).GetAttribute("value");
            if (attribute == "^4")
            {
                datarow.newrow("Number Pattern", "^4", "^4", "PASS", driver);
            }
            else
            {
                datarow.newrow("Number Pattern", "^4", attribute, "FAIL", driver);
            }
            string actual = driver.FindElement(By.Id("NumberMinLength")).GetAttribute("value");
            if (actual == "16")
            {
                datarow.newrow("Minimum Length", "16", "16", "PASS", driver);
            }
            else
            {
                datarow.newrow("Minimum Length", "16", actual, "FAIl", driver);
            }
            string str3 = driver.FindElement(By.Id("NumberMaxLength")).GetAttribute("value");
            datarow.newrow("Minimum Length", "16", str3 == "16" ? "16" : str3, "PASS", driver);
            string str4 = driver.FindElement(By.Id("NumberChecksumResult")).GetAttribute("value");
            if (str4 == "0")
            {
                datarow.newrow("NumberChecksumResult", "0", "0", "PASS", driver);
            }
            else
            {
                datarow.newrow("NumberChecksumResult", "0", str4, "FAIL", driver);
            }
            string str5 = driver.FindElement(By.Id("SecurityCodeMinLength")).GetAttribute("value");
            if (str5 == "3")
            {
                datarow.newrow("Security code Min Length", "3", "3", "PASS", driver);
            }
            else
            {
                datarow.newrow("Security code Min Length", "3", str5, "FAIL", driver);
            }
            string str6 = driver.FindElement(By.Id("SecurityCodeMaxLength")).GetAttribute("value");
            if (str6 == "3")
            {
                datarow.newrow("Security code Min Length", "3", "3", "PASS", driver);
            }
            else
            {
                datarow.newrow("Security code Min Length", "3", str6, "FAIL", driver);
            }
        }
    }
}