// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using Selenium;
    using System;
    
    internal class MositeStart
    {
        
        datarow datarow = new datarow();
        private GeneralLibrary generalLibrary;
        
        public void Mositestart(IWebDriver driver, ISelenium selenium)
        {
            this.generalLibrary = new GeneralLibrary();
            try
            {
                this.datarow.col();
              //  new Modrophenialive().modrophenialiveproducts(selenium, driver);
                new products().product(this.datarow, driver, selenium);
               // new UserJourney().UserJourn(this.datarow, driver, selenium);
               // new UserData().Userdata(this.datarow, driver, selenium);
               // new Mopaysite().MoPay(driver, selenium, this.datarow);
            }
            catch (Exception exception)
            {
                Console.Write(exception);
                string actual = exception.ToString();
                MoBankUI.Screenshot screenshot = new MoBankUI.Screenshot();
                this.datarow.newrow("Exception", "Not Expected", actual, "FAIL", driver, selenium);
                screenshot.screenshotfailed(driver, selenium);
            }
            finally
            {
                this.datarow.excelsave("MoSiteReport", driver, selenium,"teja.vellanki@mobankgroup.com");
                this.datarow.dataflush();
                driver.Quit();
            }
        }
    }
}
