// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using OpenQA.Selenium;

namespace MoBankUI.Mosite.Modrophenia
{
    internal class MositeStart
    {
        private readonly Datarow _datarow = new Datarow();

        public void Mositestart(IWebDriver driver)
        {
            new GeneralLibrary();
            try
            {
                _datarow.Col();
                //  new Modrophenialive().modrophenialiveproducts(, driver);
                new Modropheniaproducts().product(_datarow, driver);
                // new UserJourney().UserJourn(this.datarow,driver);
                // new UserData().Userdata(this.datarow,driver);
                // new Mopaysite().MoPay(driver, , this.datarow);
            }
            catch (Exception exception)
            {
                Console.Write(exception);
                var actual = exception.ToString();
                var screenshot = new Screenshot();
                _datarow.newrow("Exception", "Not Expected", actual, "FAIL", driver);
                screenshot.screenshotfailed(driver);
            }
            finally
            {
                _datarow.excelsave("MoSiteReport", driver, "teja.vellanki@mobankgroup.com");
                _datarow.Dataflush();
                driver.Quit();
            }
        }
    }
}