// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using System;
using OpenQA.Selenium;
using Selenium;

namespace MoBankUI
{
    internal class MositeStart
    {
        private readonly datarow datarow = new datarow();
        private GeneralLibrary generalLibrary;

        public void Mositestart(IWebDriver driver, ISelenium selenium)
        {
            generalLibrary = new GeneralLibrary();
            try
            {
                datarow.col();
                //  new Modrophenialive().modrophenialiveproducts(selenium, driver);
                new products().product(datarow, driver, selenium);
                // new UserJourney().UserJourn(this.datarow, driver, selenium);
                // new UserData().Userdata(this.datarow, driver, selenium);
                // new Mopaysite().MoPay(driver, selenium, this.datarow);
            }
            catch (Exception exception)
            {
                Console.Write(exception);
                string actual = exception.ToString();
                var screenshot = new Screenshot();
                datarow.newrow("Exception", "Not Expected", actual, "FAIL", driver, selenium);
                screenshot.screenshotfailed(driver, selenium);
            }
            finally
            {
                datarow.excelsave("MoSiteReport", driver, selenium, "teja.vellanki@mobankgroup.com");
                datarow.dataflush();
                driver.Quit();
            }
        }
    }
}