// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using System;
using System.Data;
using System.Threading;
using ObjectRepository;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Selenium;

namespace MoBankUI
{
    internal class modropheniaproducts
    {
        private GeneralLibrary gereneralLibrary;

        public void comparedatarow(IWebDriver driver, ISelenium selenium, datarow datarow, DataTable dt)
        {
            gereneralLibrary = new GeneralLibrary();
            DataTable table =
                gereneralLibrary.GetExcelData(@"C:\Selenium\Input Data\ModrophenialiveProducts.xlsx", "Products").Tables
                    [0];
            for (int i = 1; i < (table.Rows.Count - 1); i++)
            {
                string actual = table.Rows[i]["Product Price"].ToString();
                string str2 = table.Rows[i]["Product Title"].ToString();
                string str3 = table.Rows[i]["Product Detail"].ToString();
                string expected = table.Rows[i]["Item Number"].ToString();
                string str5 = table.Rows[i]["Variants"].ToString();
                string str6 = dt.Rows[i]["Price"].ToString();
                string str7 = dt.Rows[i]["Title"].ToString();
                string str8 = dt.Rows[i]["Detail"].ToString();
                string str9 = dt.Rows[i]["Item Number"].ToString();
                string str10 = dt.Rows[i]["Variants"].ToString();
                if (str6 == actual)
                {
                    datarow.newrow(str7 + " Price", str6, actual, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow(str7 + " Price", str6, actual, "FAIL", driver, selenium);
                }
                if (str7.ToUpper() == str2)
                {
                    datarow.newrow(str7 + " Title", str7, str2, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow(str7 + " Title", str7, str2, "FAIL", driver, selenium);
                }
                if (str8 == str3)
                {
                    datarow.newrow(str7 + " Detail", str8, str3, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow(str7 + " Detail", str8, str3, "FAIL", driver, selenium);
                }
                if (expected == str9)
                {
                    datarow.newrow(str7 + " ItemNumber", expected, str9, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow(str7 + " ItemNumber", expected, str9, "FAIL", driver, selenium);
                }
                if (str5.TrimStart(new char[0]) == str10.TrimStart(new char[0]))
                {
                    datarow.newrow(str7 + " Variants", str5, str10, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow(str7 + " Variants", str5, str10, "FAIL", driver, selenium);
                }
            }
        }

        public void product(datarow datarow, IWebDriver driver, ISelenium selenium)
        {
            string str8;
            try
            {
                var dt = new DataTable();
                dt.Columns.Add("Price");
                dt.Columns.Add("Title");
                dt.Columns.Add("Detail");
                dt.Columns.Add("Item Number");
                dt.Columns.Add("Variants");


                driver.Navigate().GoToUrl("https://qamodrophenia.mobankdev.com/");
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("//*[@id='page-home-index']/div[1]/div[2]/div[1]/ul/li[1]/div/div/a/h2"))
                      .Click();
                selenium.WaitForPageToLoad("60000");
                loop(datarow, driver, selenium, dt);
                driver.Navigate().GoToUrl("https://qamodrophenia.mobankdev.com/");
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("//body[@id='page-home-index']/div/div[2]/div/ul/li[12]/div/div/a/h2"))
                      .Click();
                selenium.WaitForPageToLoad("60000");
                loop(datarow, driver, selenium, dt);
                comparedatarow(driver, selenium, datarow, dt);

            }
            catch (Exception exception3)
            {
                str8 = exception3.ToString();
                datarow.newrow("Exception", "Not Expected", str8, "FAIL", driver, selenium);
            }
        }

        public void loop(datarow datarow, IWebDriver driver, ISelenium selenium, DataTable dt)
        {
            string str8;
            try
            {
                int j;
                int num = 1;
                int num2 = 0;
                goto Label_0449;
                Label_0099:

                //*[@id="page-categories-details"]/div[1]/div[2]/div[1]/div/div
                //*[@id="page-categories-details"]/div[1]/div[2]/div[1]/div/div/a[3]/span/span[1]
                if ((num > 1) &&selenium.IsElementPresent("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/div/div/a[3]"))
                {
                    IWebElement ele =driver.FindElement(By.XPath("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/div/div/a[3]"));
                    string cource = ele.GetAttribute("outerHTML");
                    if (cource.Contains("ui-disabled"))
                    {
                    }
                    else
                    {
                        driver.FindElement(By.XPath("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/div/div/a[3]")).Click();selenium.WaitForPageToLoad("30000");
                    }
                }
                decimal xpathCount =selenium.GetXpathCount("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/ul/li");
                for (int i = 1; i <= xpathCount; i++)
                {
                    //*[@id="page-categories-details"]/div[1]/div[2]/div[1]/ul/li[32]/div/div/a/div[2]/p
                    string text;
                    string str4;
                    string str5;
                    string str7;
                    driver.FindElement(By.XPath("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/ul/li[" + i +"]/div/div/a/div[2]/p")).Click();
                    selenium.WaitForPageToLoad("60000");
                    DataRow row = dt.NewRow();
                    j = 1;
                    string str =
                        driver.FindElement(
                            By.XPath("//*[@id='page-products-details']/div[1]/div[2]/div/div[1]/div[1]/div/p/strong"))
                              .Text;
                    string str2 = driver.FindElement(By.XPath("//html/body/div/div/div[2]/h2")).Text;
                    row[0] = str;
                    row[1] = str2;
                    if (selenium.IsElementPresent("//div[@id='Description']/div/div/div/div/p[2]"))
                    {
                        text = selenium.GetText("//div[@id='Description']/div/div/div/div/p[2]");
                        str4 = selenium.GetText("//div[@id='Description']/div/div/div/div/p/strong");
                        row[2] = text;
                        row[3] = str4;
                    }
                    else
                    {
                        text = selenium.GetText("//div[@id='Description']/div/div/div/div/p");
                        str4 = "Item Number Not Present";
                        row[2] = text;
                        row[3] = str4;
                    }
                    #region Select Options
                    try
                    {
                        if (selenium.GetXpathCount("//html/body/div/div[2]/div/div[3]/form/ul/li[2]/fieldset/div[2]/div/label/span") != 1)
                        {
                            try
                            {
                                string[] selectOptions = selenium.GetSelectOptions("id=Variants_0__OptionValue");

                                str5 = null;
                                foreach (string str6 in selectOptions)
                                {
                                    if (str6 != "Please Select")
                                    {
                                        str5 = str5 + "\r\n" + str6;
                                        new SelectElement(driver.FindElement(By.Id("Variants_0__OptionValue")))
                                            .SelectByText(str6);
                                    }
                                }
                                row[4] = str5;
                                j++;
                            }
                            catch (Exception ex)
                            {
                            }
                        } //*[@id="AddToBasketForm"]/ul/li[2]/fieldset/div[2]/div[2]/label
                        else
                        {
                            str7 = selenium.GetValue("id=Variants_0__OptionValue");
                            row[4] = str7;
                            j++;
                        }
                    }
                    catch (Exception exception1)
                    {
                        Exception exception = exception1;
                        str8 = exception.ToString();
                        // datarow.newrow("Exception at Product variants", "Exception Not Expected", str8, "FAIL",driver, selenium);
                    }
                    #endregion

                    #region Radio Buttons
                    try
                    {
                        if (j == 1)
                        {
                            bool flag;
                            str5 = null;

                            decimal count =
                                selenium.GetXpathCount("//*[@id='AddToBasketForm']/ul/li[2]/fieldset/div[2]/div");

                            for (int num6 = 0; num6 < count; num6++)
                            {
                                str7 = driver.FindElement(By.Id("OptionValue_" + num6)).GetAttribute("Value");
                                if ((str7 != "Please Select") || (str7 != null))
                                {
                                    str5 = str5 + "\r\n" + str7;
                                    selenium.Click("id=OptionValue_" + num6);
                                }
                            }


                            row[4] = str5;
                        }
                    }
                    catch (Exception exception2)
                    {
                        str8 = exception2.ToString();
                        //  datarow.newrow("Exception at Product Variants", "Exception Not Expected", str8, "FAIL",driver, selenium);
                    }
                    #endregion

                    dt.Rows.Add(row);
                    selenium.GoBack();
                    Thread.Sleep(3000);
                }
                num++;
                IWebElement elem =driver.FindElement(By.XPath("//*[@id='page-categories-details']/div[1]/div[2]/div[1]/div/div/a[3]"));
                string courc = elem.GetAttribute("outerHTML");
                if (courc.Contains("ui-disabled"))
                {
                    goto Label_0451;
                }
                num2++;

                Label_0449:
                //flag = true;
                goto Label_0099;
                Label_0451:;
            }
            catch (Exception ex)
            {
                str8 = ex.ToString();
                datarow.newrow("Exception", "Not Expected", str8, "FAIL", driver, selenium);
            }
        }
    }
}
