// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using OpenQA.Selenium;
using WebDriver_Refining;
using NUnit.Framework;
using OpenQA.Selenium.Interactions;
using WebDriver_Refining;

namespace MoBankUI
{
    [TestFixture]
    public class MoShopConsole : driverdefining
    {
        private readonly Screenshot screenshot = new Screenshot();
       
        
        [Test]
        [Category("Fixture")]
        public void Homepagetabs(IWebDriver driver, datarow datarow)
        {
            try
            {
                
                string actual = driver.Title;
               
                if (actual == "Log On : mobank.co.uk/MoShop")
                {
                    datarow.newrow("MoshopTitle", "Log On : mobank.co.uk/MoShop", actual, "PASS", driver );
                    
                }
                else
                {
                    datarow.newrow("MoshopTitle", "Log On : mobank.co.uk/MoShop", actual, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.Id("Email")).Clear();
                driver.FindElement(By.Id("Email")).SendKeys("teja.vellanki@mobankgroup.com");
                driver.FindElement(By.Id("Password")).Clear();
                driver.FindElement(By.Id("Password")).SendKeys("Apple12345");
                driver.FindElement(By.Id("LogOn_Action_LogOn")).Click();
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                IWebElement element = driver.FindElement(By.XPath("//div[@id='IndexMenu']/ul/li/ul/li/a"));
                string str2 = driver.Title;
                
                if (str2 == "mobank.co.uk/MoShop")
                {
                    datarow.newrow("MoshopHomepageTitle", "mobank.co.uk/MoShop", str2, "PASS", driver );
                   
                }
                else
                {
                    datarow.newrow("MoshopHomepageTitle", "mobank.co.uk/MoShop", str2, "FAIL", driver );
                    screenshot.screenshotfailed(driver );
                }
                //Expanding Manage and Security
                driver.FindElement(By.XPath("//li[@id='IndexMenuLeaf1']/span")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("//li[@id='IndexMenuLeaf8']/span")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.LinkText("Scrapes")).Click();
                  waitforpagetoload(driver,30000);
                string str3 = driver.Title;


                if (str3 == "Scrapes : mobank.co.uk/MoShop")
                {
                    datarow.newrow("Scrape Page", "Scrapes : mobank.co.uk/MoShop", str3, "PASS", driver );
                }
                else
                {
                    datarow.newrow("Scrape Page", "Scrapes : mobank.co.uk/MoShop", str3, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Shops')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                string str4 = driver.Title;
                if (str4 == "Shops : mobank.co.uk/MoShop")
                {
                    datarow.newrow("Shops Page", "Scrapes : mobank.co.uk/MoShop", str4, "PASS", driver);
                }
                else
                {
                    datarow.newrow("Shops Page", "Scrapes : mobank.co.uk/MoShop", str4, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                 driver.FindElement(By.LinkText("MoShop")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Global Customisations')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                string str5 = driver.Title;
                if (str5 == "Global Customisations : mobank.co.uk/MoShop")
                {
                    datarow.newrow("Global Customerisations Page", "Global Customisations : mobank.co.uk/MoShop", str5,"PASS", driver);
                }
                else
                {
                    datarow.newrow("Global Customerisations Page", "Global Customisations : mobank.co.uk/MoShop", str5,"FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Transformations')])[2]")).Click();
                waitforpagetoload(driver,30000);
                string str6 = driver.Title;
                if (str6 == "Transformations : mobank.co.uk/MoShop")
                {
                    datarow.newrow("Transformations Page", "Transformations : mobank.co.uk/MoShop", str6, "PASS", driver);
                }
                else
                {
                    datarow.newrow("Transformations Page", "Transformations : mobank.co.uk/MoShop", str6, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                  waitforpagetoload(driver,30000);


                driver.FindElement(By.XPath("(//a[contains(text(),'Global Settings')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                string str7 = driver.Title;
                if (str7 == "mobank.co.uk/MoShop")
                {
                    datarow.newrow("Global settings Page", "mobank.co.uk/MoShop", str7, "PASS", driver);
                }
                else
                {
                    datarow.newrow("Global settings Page", "mobank.co.uk/MoShop", str7, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Security')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                string str8 = driver.Title;
                if (str8 == "mobank.co.uk/MoShop")
                {
                    datarow.newrow("Security Page", "mobank.co.uk/MoShop", str8, "PASS", driver);
                }
                else
                {
                    datarow.newrow("Security Page", "mobank.co.uk/MoShop", str8, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.CssSelector("#IndexMenu > ul > li > a")).Click();
                   waitforpagetoload(driver,30000);
                 driver.FindElement(By.XPath("(//a[contains(text(),'Security')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Groups')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                driver.FindElement(By.LinkText("MoShop")).Click();
                   waitforpagetoload(driver,30000);
                driver.FindElement(By.XPath("(//a[contains(text(),'Teja Vellanki')])[2]")).Click();
                  waitforpagetoload(driver,30000);
                string str9 = driver.Title;
                if (str9 == "Teja Vellanki : mobank.co.uk/MoShop")
                {
                    datarow.newrow("Account Page", "Teja Vellanki : mobank.co.uk/MoShop", str9, "PASS", driver);
                }
                else
                {
                    datarow.newrow("Account Page", "Teja Vellanki : mobank.co.uk/MoShop", str9, "FAIL", driver);
                    screenshot.screenshotfailed(driver);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                waitforpagetoload(driver,30000);
            }
            catch (Exception exception3)
            {
                string str10 = exception3.ToString();
                datarow.newrow("Exception", "Exception Not Expected", str10, "FAIL", driver);
            }
        }

        private bool IsElementPresent(By by, IWebDriver driver)
        {
            try
            {
                driver.FindElement(by);
                return true;
            }
            catch (NoSuchElementException)
            {
                return false;
            }
        }

        
    }
}