// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using OpenQA.Selenium.Support.UI;
    using Selenium;
    using System;
    using System.Threading;
    
    internal class Scheduler
    {
        public void schedule(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            int num;
            string str4;
            string str5;
            string str6;
            string str7;
            string str8;
            string str9;
            string str10;
            string str11;
            string str12;
            string str13;
            driver.FindElement(By.LinkText("Shop")).Click();
            selenium.WaitForPageToLoad("30000");
            driver.FindElement(By.LinkText("Scheduler")).Click();
            selenium.WaitForPageToLoad("30000");
            datarow.newrow("", "", "SCHEDULER", "", driver, selenium);
            if (selenium.IsElementPresent("css=h3.collapsible.collapsed"))
            {
                driver.FindElement(By.CssSelector("h3.collapsible.collapsed")).Click();
            }
            string str = selenium.GetValue("Jobs_0__JobType");
            if (str == "")
            {
                new SelectElement(driver.FindElement(By.Id("Jobs_0__JobType"))).SelectByText("Scrape");
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                string attribute = driver.FindElement(By.Id("Jobs_0__JobType")).GetAttribute("Value");
                if (attribute == "Scrape")
                {
                    datarow.newrow("Job Type", "Scrape", attribute, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Job Type", "Scrape", attribute, "FAIL", driver, selenium);
                }
                driver.FindElement(By.Id("Jobs_0__Active")).Click();
                driver.FindElement(By.Id("Jobs_0__StartOn")).Clear();
                driver.FindElement(By.Id("Jobs_0__StartOn")).SendKeys("7/31/2012 11:19:00 AM");
                driver.FindElement(By.Id("Jobs_0__EndOn")).Clear();
                driver.FindElement(By.Id("Jobs_0__EndOn")).SendKeys("7/31/2013 11:19:00 AM");
                driver.FindElement(By.Id("Jobs_0__RepeatInterval_Days")).Clear();
                driver.FindElement(By.Id("Jobs_0__RepeatInterval_Days")).SendKeys("1");
                driver.FindElement(By.Id("Jobs_0__RepeatInterval_Hours")).Clear();
                driver.FindElement(By.Id("Jobs_0__RepeatInterval_Hours")).SendKeys("24");
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                new SelectElement(driver.FindElement(By.Id("Jobs_1__JobType"))).SelectByText("Data Feed");
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                Thread.Sleep(0x1388);
                string str3 = selenium.GetValue("id=Jobs_1__Active");
                num = 0;
                if (str3 == "on")
                {
                    num = 1;
                }
                str4 = driver.FindElement(By.Id("Jobs_" + num + "__Active")).GetAttribute("Value");
                str5 = driver.FindElement(By.Id("Jobs_" + num + "__StartOn")).GetAttribute("Value");
                str6 = driver.FindElement(By.Id("Jobs_" + num + "__EndOn")).GetAttribute("Value");
                str7 = driver.FindElement(By.Id("Jobs_" + num + "__RepeatInterval_Days")).GetAttribute("Value");
                str8 = driver.FindElement(By.Id("Jobs_" + num + "__RepeatInterval_Hours")).GetAttribute("Value");
                #region validation
                if (str4 == "true")
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Activated", str4, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Not Activated", str4, "FAIL", driver, selenium);
                }
                if (str5 == "7/31/2012 11:19:00 AM")
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "FAIL", driver, selenium);
                }
                if (str6 == "7/31/2013 11:19:00 AM")
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                if (str7 == "2")
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "FAIL", driver, selenium);
                }
                if (str8 == "0")
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "FAIL", driver, selenium);
                }
                #endregion
                if (str3 == "off")
                {
                    driver.FindElement(By.Id("Jobs_1__Active")).Click();
                    driver.FindElement(By.Id("Jobs_1__Url")).Clear();
                    driver.FindElement(By.Id("Jobs_1__Url")).SendKeys("https://dl.dropbox.com/u/93702113/test-catalogue-small.xml");
                    driver.FindElement(By.Id("Jobs_1__StartOn")).Clear();
                    driver.FindElement(By.Id("Jobs_1__StartOn")).SendKeys("7/31/2012 11:19:00 AM");
                    driver.FindElement(By.Id("Jobs_1__EndOn")).Clear();
                    driver.FindElement(By.Id("Jobs_1__EndOn")).SendKeys("7/31/2013 11:19:00 AM");
                    driver.FindElement(By.Id("Jobs_1__RepeatInterval_Days")).Clear();
                    driver.FindElement(By.Id("Jobs_1__RepeatInterval_Days")).SendKeys("1");
                    driver.FindElement(By.Id("Jobs_1__RepeatInterval_Hours")).Clear();
                    driver.FindElement(By.Id("Jobs_1__RepeatInterval_Hours")).SendKeys("1");
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                }
                else
                {
                    driver.FindElement(By.Id("Jobs_0__Active")).Click();
                    driver.FindElement(By.Id("Jobs_0__Url")).Clear();
                    driver.FindElement(By.Id("Jobs_0__Url")).SendKeys("https://dl.dropbox.com/u/93702113/test-catalogue-small.xml");
                    driver.FindElement(By.Id("Jobs_0__StartOn")).Clear();
                    driver.FindElement(By.Id("Jobs_0__StartOn")).SendKeys("7/31/2012 11:19:00 AM");
                    driver.FindElement(By.Id("Jobs_0__EndOn")).Clear();
                    driver.FindElement(By.Id("Jobs_0__EndOn")).SendKeys("7/31/2013 11:19:00 AM");
                    driver.FindElement(By.Id("Jobs_0__RepeatInterval_Days")).Clear();
                    driver.FindElement(By.Id("Jobs_0__RepeatInterval_Days")).SendKeys("1");
                    driver.FindElement(By.Id("Jobs_0__RepeatInterval_Hours")).Clear();
                    driver.FindElement(By.Id("Jobs_0__RepeatInterval_Hours")).SendKeys("1");
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                }
                int num2 = 0;
                if (str3 == "off")
                {
                    num2 = 1;
                }
                str9 = driver.FindElement(By.Id("Jobs_" + num2 + "__Active")).GetAttribute("Value");
                str10 = driver.FindElement(By.Id("Jobs_" + num2 + "__StartOn")).GetAttribute("Value");
                str11 = driver.FindElement(By.Id("Jobs_" + num2 + "__EndOn")).GetAttribute("Value");
                str12 = driver.FindElement(By.Id("Jobs_" + num2 + "__RepeatInterval_Days")).GetAttribute("Value");
                str13 = driver.FindElement(By.Id("Jobs_" + num2 + "__RepeatInterval_Hours")).GetAttribute("Value");
                #region validations
                if (str9 == "true")
                {
                    datarow.newrow("Scheduler DataFeed Activation", "DataFeed Activated", str9, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler DataFeed Activation", "DataFeed Not Activated", str9, "FAIL", driver, selenium);
                }
                if (str10 == "7/31/2012 11:19:00 AM")
                {
                    datarow.newrow("Scheduler Start Time", "7/31/2012 11:19:00 AM", str10, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler Start Time", "7/31/2012 11:19:00 AM", str10, "FAIL", driver, selenium);
                }
                if (str11 == "7/31/2013 11:19:00 AM")
                {
                    datarow.newrow("Scheduler End Time", "7/31/2013 11:19:00 AM", str11, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler End Time", "7/31/2013 11:19:00 AM", str11, "PASS", driver, selenium);
                }
                if (str12 == "1")
                {
                    datarow.newrow("Repeat interval Days", "1", str12, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Days", "1", str12, "FAIL", driver, selenium);
                }
                if (str13 == "0")
                {
                    datarow.newrow("Repeat interval Hours", "1", str13, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Hours", "1", str13, "FAIL", driver, selenium);
                }
                #endregion
            }
            else if (str != "")
            {
                #region Validations
                num = 0;
                str4 = driver.FindElement(By.Id("Jobs_" + num + "__Active")).GetAttribute("Value");
                str5 = driver.FindElement(By.Id("Jobs_" + num + "__StartOn")).GetAttribute("Value");
                str6 = driver.FindElement(By.Id("Jobs_" + num + "__EndOn")).GetAttribute("Value");
                str7 = driver.FindElement(By.Id("Jobs_" + num + "__RepeatInterval_Days")).GetAttribute("Value");
                str8 = driver.FindElement(By.Id("Jobs_" + num + "__RepeatInterval_Hours")).GetAttribute("Value");
              
                if (str4 == "true")
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Activated", str4, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Not Activated", str4, "FAIL", driver, selenium);
                }
                if (str5 == "7/31/2012 11:19:00 AM")
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "FAIL", driver, selenium);
                }
                if (str6 == "7/31/2013 11:19:00 AM")
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                if (str7 == "2")
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "FAIL", driver, selenium);
                }
                if (str8 == "0")
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "FAIL", driver, selenium);
                }

                int num3 = 1;
                str9 = driver.FindElement(By.Id("Jobs_" + num3 + "__Active")).GetAttribute("Value");
                str10 = driver.FindElement(By.Id("Jobs_" + num3 + "__StartOn")).GetAttribute("Value");
                str11 = driver.FindElement(By.Id("Jobs_" + num3 + "__EndOn")).GetAttribute("Value");
                str12 = driver.FindElement(By.Id("Jobs_" + num3 + "__RepeatInterval_Days")).GetAttribute("Value");
                str13 = driver.FindElement(By.Id("Jobs_" + num3 + "__RepeatInterval_Hours")).GetAttribute("Value");
                if (str9 == "true")
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Activated", str4, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Scheduler Scrape Activation", "Scrape Not Activated", str4, "FAIL", driver, selenium);
                }
                if (str10 == "7/31/2012 11:19:00 AM")
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler Start Time", "7/31/2012 11:19:00 AM", str5, "FAIL", driver, selenium);
                }
                if (str11 == "7/31/2013 11:19:00 AM")
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Schduler End Time", "7/31/2013 11:19:00 AM", str6, "PASS", driver, selenium);
                }
                if (str12 == "2")
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Days", "2", str7, "FAIL", driver, selenium);
                }
                if (str13 == "24")
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Repeat interval Hours", "0", str8, "FAIL", driver, selenium);
                }
                #endregion
            }
               
            new Checkout().checkout(driver, selenium, datarow);
        }
    }
}
