// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using OpenQA.Selenium.Support.UI;
    using Selenium;
    using System;
    using System.Threading;
    
    internal class LookandFeel
    {
        public void lookandfeel(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            datarow.newrow("", "", "LOOK AND FEEL TAB", "", driver, selenium);
            driver.FindElement(By.XPath("(//a[contains(text(),'Shops')])[2]")).Click();
            selenium.WaitForPageToLoad("30000");
            Thread.Sleep(0x2710);
            driver.FindElement(By.LinkText("Testshop")).Click();
            selenium.WaitForPageToLoad("30000");
            string actual = driver.Title.ToString();
            if (actual == "Shop : mobank.co.uk/MoShop")
            {
                datarow.newrow("ShopTitle", "Shop : mobank.co.uk/MoShop", actual, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("ShopTitle", "Shop : mobank.co.uk/MoShop", actual, "FAIL", driver, selenium);
            }
            driver.FindElement(By.LinkText("Look & Feel")).Click();
            selenium.WaitForPageToLoad("30000");
            if (driver.Title.ToString() == "Look & Feel : mobank.co.uk/MoShop")
            {
                datarow.newrow("LookAndFeel", "Look & Feel : mobank.co.uk/MoShop", actual, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("LookAndFeel", "Look & Feel : mobank.co.uk/MoShop", actual, "FAIL", driver, selenium);
            }
            int num = 0;
            while (true)
            {
                driver.FindElement(By.Id("Customisations_0__Title")).Clear();
                driver.FindElement(By.Id("Customisations_0__Title")).SendKeys("QA-TestShop");
                Thread.Sleep(0x7d0);
                driver.FindElement(By.CssSelector("input.button")).Click();
                selenium.WaitForPageToLoad("30000");
                string attribute = driver.FindElement(By.Id("Customisations_0__Title")).GetAttribute("Value");
                if (attribute == "QA-TestShop")
                {
                    datarow.newrow("Customiastion Title", "QA-TestShop", attribute, "PASS", driver, selenium);
                    driver.FindElement(By.XPath("(//input[@id='DefaultCustomisationsId'])[2]")).Click();
                    selenium.WaitForPageToLoad("30000");
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                    driver.FindElement(By.XPath("(//a[contains(text(),'…')])[2]")).Click();
                    selenium.WaitForPageToLoad("30000");
                    string str4 = driver.Title.ToString();
                    if (str4 == "Customisation : mobank.co.uk/MoShop")
                    {
                        datarow.newrow("Customisation Title", "Customisation : mobank.co.uk/MoShop", str4, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Customisation Title", "Customisation : mobank.co.uk/MoShop", str4, "FAIL", driver, selenium);
                    }
                    decimal xpathCount = selenium.GetXpathCount("//form[@id='customisation-page-update-form']/div");
                    for (int i = 1; i <= xpathCount; i++)
                    {
                        try
                        {
                            selenium.Click("//form[@id='customisation-page-update-form']/div[" + i + "]/h3");
                        }
                        catch (Exception)
                        {
                        }
                    }
                    new SelectElement(driver.FindElement(By.Id("ExternalLinks_0__ExternalLinkConfigId"))).SelectByText("Twitter");
                    driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).Clear();
                    driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).SendKeys("ticklecompany");
                    driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).Clear();
                    driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).SendKeys("Your order number is {0}.");
                    driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).Clear();
                    driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).SendKeys("Your order has been succesfull");
                    driver.FindElement(By.Id("OrderConfirmationFailureMessage")).Clear();
                    driver.FindElement(By.Id("OrderConfirmationFailureMessage")).SendKeys("Your order couldnot be processed.");
                    driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).Clear();
                    driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).SendKeys("Your order couldnot be processed.");
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                    Thread.Sleep(0x1388);
                    string str5 = driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).GetAttribute("Value");
                    string str6 = driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).GetAttribute("Value");
                    string str7 = driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).GetAttribute("Value");
                    string str8 = driver.FindElement(By.Id("OrderConfirmationFailureMessage")).GetAttribute("Value");
                    string str9 = driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).GetAttribute("Value");
                    if (str5 == "ticklecompany")
                    {
                        datarow.newrow("Link Replacement", "ticklecompany", str5, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Link Replacement", "ticklecompany", str5, "FAIL", driver, selenium);
                    }
                    if (str6 == "Your order number is {0}.")
                    {
                        datarow.newrow("Order Confirmation", "Your order number is {0}.", str6, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Order Confirmation", "Your order number is {0}.", str6, "FAIL", driver, selenium);
                    }
                    if (str7 == "Your order has been succesfull")
                    {
                        datarow.newrow("ConfirmSuccess", "Your order has been succesfull", str7, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("ConfirmSuccess", "Your order has been succesfull", str7, "FAIL", driver, selenium);
                    }
                    if (str8 == "Your order couldnot be processed.")
                    {
                        datarow.newrow("Confirm Failure", "Your order couldnot be processed.", str8, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Confirm Failure", "Your order couldnot be processed.", str8, "FAIL", driver, selenium);
                    }
                    if (str9 == "Your order couldnot be processed.")
                    {
                        datarow.newrow("Confirm Declined", "Your order couldnot be processed.", str9, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Confirm Declined", "Your order couldnot be processed.", str9, "FAIL", driver, selenium);
                    }
                    new SelectElement(driver.FindElement(By.Id("ExternalLinks_1__ExternalLinkConfigId"))).SelectByText("Facebook");
                    driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).Clear();
                    driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).SendKeys("TheTickleCompany");
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                    string str10 = driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).GetAttribute("Value");
                    if (str10 == "TheTickleCompany")
                    {
                        datarow.newrow("Link Replacement1", "TheTickleCompany", str10, "PASS", driver, selenium);
                    }
                    else
                    {
                        datarow.newrow("Link Replacement1", "TheTickleCompany", str10, "FAIL", driver, selenium);
                    }
                    driver.FindElement(By.CssSelector("input.button")).Click();
                    selenium.WaitForPageToLoad("30000");
                    new Scheduler().schedule(driver, selenium, datarow);
                    return;
                }
                datarow.newrow("Customiastion Title", "QA-TestShop", attribute, "FAIL", driver, selenium);
                num++;
            }
        }
    }
}
