// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using OpenQA.Selenium.Support.UI;
    using Selenium;
    using System;
    
    internal class Confirm
    {
        public void confirm(IWebDriver driver, ISelenium selenium, datarow datarow)
        {
            datarow.newrow("", "", "CONFIRM CONFIGURATION", "", driver, selenium);
            driver.FindElement(By.XPath("(//a[contains(text(),'…')])[3]")).Click();
            selenium.WaitForPageToLoad("30000");
            driver.FindElement(By.Id("Url")).Clear();
            driver.FindElement(By.Id("Url")).SendKeys("https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl");
            driver.FindElement(By.Id("Parameters")).Clear();
            driver.FindElement(By.Id("Parameters")).SendKeys("RANDOM=0.825800705309124&ACTION=GETPSPFORM&PAYMENTMETHOD=4");
            driver.FindElement(By.Id("Sequence")).Clear();
            driver.FindElement(By.Id("Sequence")).SendKeys("30");
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Selector")).Clear();
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Selector")).SendKeys("input[name=ORDERNUMBER]");
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Attribute")).Clear();
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Attribute")).SendKeys("value");
            new SelectElement(driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__PropertyPath"))).SelectByText("Reference");
            driver.FindElement(By.CssSelector("input.button")).Click();
            selenium.WaitForPageToLoad("30000");
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Selector")).Clear();
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Selector")).SendKeys("input[name=\"CALLBACKURLUSER\"]");
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Attribute")).Clear();
            driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Attribute")).SendKeys("value");
            new SelectElement(driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__PropertyPath"))).SelectByText("PaymentAcceptedUrl");
            driver.FindElement(By.CssSelector("input.button")).Click();
            string attribute = driver.FindElement(By.Id("Url")).GetAttribute("Value");
            string actual = driver.FindElement(By.Id("Parameters")).GetAttribute("Value");
            string str3 = driver.FindElement(By.Id("Sequence")).GetAttribute("Value");
            string str4 = driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Selector")).GetAttribute("Value");
            string str5 = driver.FindElement(By.Id("ScrapedDataValueConfigurations_0__Attribute")).GetAttribute("Value");
            string str6 = driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Selector")).GetAttribute("Value");
            string str7 = driver.FindElement(By.Id("ScrapedDataValueConfigurations_1__Attribute")).GetAttribute("Value");
            if (attribute == "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl")
            {
                datarow.newrow("URL", "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl", attribute, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("URL", "https://www.the-tickle-company.co.uk/cgi-bin/os000001.pl", attribute, "FAIL", driver, selenium);
            }
            if (actual == "RANDOM=0.825800705309124&ACTION=GETPSPFORM&PAYMENTMETHOD=4")
            {
                datarow.newrow("Parameters", "RANDOM=0.825800705309124&ACTION=GETPSPFORM&PAYMENTMETHOD=4", actual, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Parameters", "RANDOM=0.825800705309124&ACTION=GETPSPFORM&PAYMENTMETHOD=4", actual, "PASS", driver, selenium);
            }
            if (str3 == "30")
            {
                datarow.newrow("Sequence", "30", str3, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Sequence", "30", str3, "FAIL", driver, selenium);
            }
            if (str4 == "input[name=ORDERNUMBER]")
            {
                datarow.newrow("Scraped Data", "input[name=ORDERNUMBER]", str4, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Scraped Data", "input[name=ORDERNUMBER]", str4, "FAIL", driver, selenium);
            }
            if (str5 == "value")
            {
                datarow.newrow("Scrapped Data Configuration", "value", str5, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Scrapped Data Configuration", "value", str5, "FAIL", driver, selenium);
            }
            if (str6 == "input[name=\"CALLBACKURLUSER\"]")
            {
                datarow.newrow("Scraped Data Selector1", "input[name=\"CALLBACKURLUSER\"]", str6, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Scraped Data Selector1", "input[name=\"CALLBACKURLUSER\"]", str6, "PASS", driver, selenium);
            }
            if (str7 == "value")
            {
                datarow.newrow("Scraped Data Configuration1", "value", str7, "PASS", driver, selenium);
            }
            else
            {
                datarow.newrow("Scraped Data Configuration1", "value", str7, "FAIL", driver, selenium);
            }
        }
    }
}
