// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium.Support.UI;
using WebDriver_Refining;

using OpenQA.Selenium;
 

namespace MoBankUI
{
    public class LookandFeel : driverdefining
    {
        [Test]
        public void lookandfeel(IWebDriver driver, datarow datarow)
        {
            try
            {
                datarow.newrow("", "", "LOOK AND FEEL TAB", "", driver);
                driver.FindElement(By.LinkText("Look & Feel")).Click();
                  waitforpagetoload(driver,30000);
                string actual = driver.Title;
                if (driver.Title == "Look & Feel : mobank.co.uk/MoShop")
                {
                    datarow.newrow("LookAndFeel", "Look & Feel : mobank.co.uk/MoShop", actual, "PASS", driver);
                }
                else
                {
                    datarow.newrow("LookAndFeel", "Look & Feel : mobank.co.uk/MoShop", actual, "FAIL", driver);
                }
                int num = 0;
               
                    for (int i = 0;; i++)
                    {
                        driver.FindElement(By.Id("Customisations_0__Title")).Clear();
                        driver.FindElement(By.Id("Customisations_0__Title")).SendKeys("QA-TestShop");
                        Thread.Sleep(2000);
                        //Focus("id=Customisations_0__Title");
                        driver.FindElement(By.Id("Customisations_0__Title")).SendKeys(Keys.Enter);
                        waitforpagetoload(driver,30000);
                        driver.FindElement(By.CssSelector("input.button")).Click();
                        waitforpagetoload(driver,30000);

                        string attribute = driver.FindElement(By.Id("Customisations_0__Title")).GetAttribute("Value");
                        if (attribute == "QA-TestShop")
                        {
                            break;
                        }
                    }

                    string attriute = driver.FindElement(By.Id("Customisations_0__Title")).GetAttribute("Value");
                    if (attriute == "QA-TestShop")
                    {
                        try
                        {
                        datarow.newrow("Customiastion Title", "QA-TestShop", attriute, "PASS", driver);
                        driver.FindElement(By.XPath("(//input[@id='DefaultCustomisationsId'])[2]")).Click();
                          waitforpagetoload(driver,30000);
                        driver.FindElement(By.CssSelector("input.button")).Click();
                         waitforpagetoload(driver,30000);
                        driver.FindElement(By.XPath("(//a[contains(text(),'…')])[2]")).Click();
                          waitforpagetoload(driver,30000);
                        string str4 = driver.Title;
                        if (str4 == "Customisation : mobank.co.uk/MoShop")
                        {
                            datarow.newrow("Customisation Title", "Customisation : mobank.co.uk/MoShop", str4, "PASS",driver);
                        }
                        else
                        {
                            datarow.newrow("Customisation Title", "Customisation : mobank.co.uk/MoShop", str4, "FAIL",driver);
                        }
                        for (int j = 3; j <= 8; j++)
                        {
                            if(driver.FindElement(By.CssSelector("h3.collapsible.collapsed")).Displayed)
                            {
                                driver.FindElement(By.CssSelector("h3.collapsible.collapsed")).Click();
                            }
                            //*[@id="customisation-page-update-form"]/div[3]/h3
                        }

                        }
                         catch (Exception ex)
                         {

                             string e = ex.ToString();
                         }
                        try
                        {

                            Selectanoption(driver, By.Id("ExternalLinks_0__ExternalLinkConfigId"), "Feefo");
                       
                       // new SelectElement(driver.FindElement(By.Id("ExternalLinks_0__ExternalLinkConfigId"))).SelectByText("Feefo");
                        driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).Clear();
                        driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).SendKeys("ticklecompany");
                        driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).Clear();
                        driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).SendKeys("Your order number is {0}.");
                        driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).Clear();
                        driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).SendKeys("Your order has been succesfull");
                        driver.FindElement(By.Id("OrderConfirmationFailureMessage")).Clear();
                        driver.FindElement(By.Id("OrderConfirmationFailureMessage")).SendKeys("Your order couldnot be processed.");
                        driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).Clear();
                        driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).SendKeys("Your order couldnot be processed.");
                        driver.FindElement(By.CssSelector("input.button")).Click();
                        waitforpagetoload(driver,30000);
                        Thread.Sleep(0x1388);
                        }
                        catch (Exception ex)
                        {

                            string e = ex.ToString();
                        }
                        #region Validations

                        string str5 = driver.FindElement(By.Id("ExternalLinks_0__LinkReplacement")).GetAttribute("Value");
                        string str6 = driver.FindElement(By.Id("OrderConfirmationOrderNumberText")).GetAttribute("Value");
                        string str7 = driver.FindElement(By.Id("OrderConfirmationSuccessMessage")).GetAttribute("Value");
                        string str8 = driver.FindElement(By.Id("OrderConfirmationFailureMessage")).GetAttribute("Value");
                        string str9 = driver.FindElement(By.Id("OrderConfirmationDeclinedMessage")).GetAttribute("Value");
                        if (str5 == "ticklecompany")
                        {
                            datarow.newrow("Link Replacement", "ticklecompany", str5, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("Link Replacement", "ticklecompany", str5, "FAIL", driver);
                        }
                        if (str6 == "Your order number is {0}.")
                        {
                            datarow.newrow("Order Confirmation", "Your order number is {0}.", str6, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("Order Confirmation", "Your order number is {0}.", str6, "FAIL", driver);
                        }
                        if (str7 == "Your order has been succesfull")
                        {
                            datarow.newrow("ConfirmSuccess", "Your order has been succesfull", str7, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("ConfirmSuccess", "Your order has been succesfull", str7, "FAIL", driver);
                        }
                        if (str8 == "Your order couldnot be processed.")
                        {
                            datarow.newrow("Confirm Failure", "Your order couldnot be processed.", str8, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("Confirm Failure", "Your order couldnot be processed.", str8, "FAIL", driver);
                        }
                        if (str9 == "Your order couldnot be processed.")
                        {
                            datarow.newrow("Confirm Declined", "Your order couldnot be processed.", str9, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("Confirm Declined", "Your order couldnot be processed.", str9, "FAIL", driver);
                        }

                        #endregion
                        Selectanoption(driver, By.Id("ExternalLinks_1__ExternalLinkConfigId"), "Facebook");

                        //new SelectElement(driver.FindElement(By.Id("ExternalLinks_1__ExternalLinkConfigId"))).SelectByText("Facebook");
                        driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).Clear();
                        driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).SendKeys("TheTickleCompany");
                        driver.FindElement(By.CssSelector("input.button")).Click();
                          waitforpagetoload(driver,30000);
                        string str10 =
                            driver.FindElement(By.Id("ExternalLinks_1__LinkReplacement")).GetAttribute("Value");
                        if (str10 == "TheTickleCompany")
                        {
                            datarow.newrow("Link Replacement1", "TheTickleCompany", str10, "PASS", driver);
                        }
                        else
                        {
                            datarow.newrow("Link Replacement1", "TheTickleCompany", str10, "FAIL", driver);
                        }
                        driver.FindElement(By.CssSelector("input.button")).Click();
                        waitforpagetoload(driver,30000);
                       
                    }
                
            }
            catch (Exception ex)
            {
                string e = ex.ToString();
                datarow.newrow("Exception", "Exception Not Expected", e, "FAIL", driver);
            }
            LookandFeelImages images = new LookandFeelImages();
            images.images(driver,datarow);
            new Scheduler().schedule(driver,datarow);
        }
    }
}