// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using Selenium;
    using System;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.Globalization;
    
    public class Screenshot
    {
        public WebDriverBackedSelenium selenium;
        
        public void screenshotfailed(IWebDriver driver, ISelenium selenium)
        {
            using (Bitmap bitmap = new Bitmap(100, 100))
            {
                string str = DateTime.Now.Year.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Month.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Day.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Hour.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Minute.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Second.ToString(CultureInfo.InvariantCulture);
                string filename = @"C:\Selenium\Input Data\FailedScreenshots\" + str + ".png";
                bitmap.Save(filename, ImageFormat.Png);
                ((ITakesScreenshot) driver).GetScreenshot().SaveAsFile(filename, ImageFormat.Png);
            }
        }
        
        public void screenshotnotifications(IWebDriver driver, ISelenium selenium)
        {
            selenium.Open("http://ec2-174-129-69-123.compute-1.amazonaws.com:8080/notify/show");
            selenium.WaitForPageToLoad("30000");
            using (Bitmap bitmap = new Bitmap(50, 50))
            {
                string str = DateTime.Now.Year.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Month.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Day.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Hour.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Minute.ToString(CultureInfo.InvariantCulture) + DateTime.Now.Second.ToString(CultureInfo.InvariantCulture);
                string filename = @"C:\Selenium\Input Data\Callback" + str + ".png";
                bitmap.Save(filename, ImageFormat.Png);
                ((ITakesScreenshot) driver).GetScreenshot().SaveAsFile(filename, ImageFormat.Png);
            }
        }
    }
}
