// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe

using System;
using System.Threading;
using OpenQA.Selenium;
using Selenium;

namespace MoBankUI
{
    internal class HomepageTabsModrophenia
    {
        public void HomepageTabsModro(string HomepageTitle, string aboutus, string shipping, string terms,
                                      datarow datarow, IWebDriver driver, ISelenium selenium)
        {
            driver.FindElement(By.CssSelector("img")).Click();
            selenium.WaitForPageToLoad("30000");
            decimal xpathCount = selenium.GetXpathCount("//body[@id='page-home-index']/div/div[3]/ul/li");
            for (int i = 1; i <= xpathCount; i++)
            {
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                IWebElement element =
                    driver.FindElement(By.XPath("//body[@id='page-home-index']/div/div[3]/ul/li[" + i + "]/div/div/a"));
                driver.FindElement(By.XPath("//body[@id='page-home-index']/div/div[3]/ul/li[" + i + "]/div/div/a"))
                      .Click();
                selenium.WaitForPageToLoad("30000");
                Thread.Sleep(3000);
                string actual = driver.Title;
                if (i > 1)
                {
                    selenium.GoBack();
                    selenium.WaitForPageToLoad("30000");
                }
                switch (i)
                {
                    case 1:
                        if (HomepageTitle == actual)
                        {
                            datarow.newrow("HomepageTitle", HomepageTitle, actual, "PASS", driver, selenium);
                        }
                        else
                        {
                            datarow.newrow("HomepageTitle", HomepageTitle, actual, "FAIL", driver, selenium);
                        }
                        break;

                    case 2:
                        if (aboutus == actual)
                        {
                            datarow.newrow("AboutUS", aboutus, actual, "PASS", driver, selenium);
                        }
                        else
                        {
                            datarow.newrow("AboutUS", aboutus, actual, "FAIL", driver, selenium);
                        }
                        break;

                    case 3:
                        if (shipping == actual)
                        {
                            datarow.newrow("Shipping", shipping, actual, "PASS", driver, selenium);
                        }
                        else
                        {
                            datarow.newrow("Shipping", shipping, actual, "FAIL", driver, selenium);
                        }
                        break;

                    case 4:
                        if (terms == actual)
                        {
                            datarow.newrow("Terms And Conditions", terms, actual, "PASS", driver, selenium);
                        }
                        else
                        {
                            datarow.newrow("Terms And Conditions", terms, actual, "FAIL", driver, selenium);
                        }
                        break;
                }
            }
        }
    }
}