// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using System.Threading;
using OpenQA.Selenium;

namespace MoBankUI.MoSite.Other
{
    internal class HomepageTabsModrophenia : Driverdefining
    {
        public void HomepageTabsModro(string homepageTitle, string aboutus, string shipping, string terms,
                                      Datarow datarow, IWebDriver driver)
        {
            driver.FindElement(By.CssSelector("img")).Click();

            var xpathCount = GetXpathCount(driver, "//body[@id='page-home-index']/div/div[3]/ul/li");
            for (var i = 1; i <= xpathCount; i++)
            {
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                driver.FindElement(By.XPath("//body[@id='page-home-index']/div/div[3]/ul/li[" + i + "]/div/div/a"));
                driver.FindElement(By.XPath("//body[@id='page-home-index']/div/div[3]/ul/li[" + i + "]/div/div/a"))
                      .Click();


                Thread.Sleep(3000);
                var actual = driver.Title;
                if (i > 1)
                {
                    driver.Navigate().Back();
                }
                switch (i)
                {
                    case 1:
                        datarow.Newrow("HomepageTitle", homepageTitle, actual, homepageTitle == actual ? "PASS" : "FAIL",
                            driver);
                        break;

                    case 2:
                        datarow.Newrow("AboutUS", aboutus, actual, aboutus == actual ? "PASS" : "FAIL", driver);
                        break;

                    case 3:
                        datarow.Newrow("Shipping", shipping, actual, shipping == actual ? "PASS" : "FAIL", driver);
                        break;

                    case 4:
                        datarow.Newrow("Terms And Conditions", terms, actual, terms == actual ? "PASS" : "FAIL", driver);
                        break;
                }
            }
        }
    }
}