// Generated by .NET Reflector from C:\Program Files\Default Company Name\ Test Tool\MoBankUI.exe

using System;
using OpenQA.Selenium;

namespace MoBankUI.MoSite.Other
{
    internal class Homepagelinks : Driverdefining
    {
        public void HompageLinks(Datarow datarow, IWebDriver driver)
        {
            var excelData = new GeneralLibrary().GetExcelData(@"C:\\Input Data\Object Repository.xls",
                                                                  "Modrophenia");
            driver.FindElement(By.CssSelector("img")).Click();

            decimal count = driver.FindElements(By.XPath("//html/body/div/div[2]/div/ul/li")).Count;
            var num2 = 0;
            for (var i = 1; i <= count; i++)
            {
                var table = excelData.Tables[0];
                var actual = table.Rows[num2]["HomePageLinks"].ToString();
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                driver.FindElement(By.XPath("//html/body/div/div[2]/div/ul/li[" + i + "]/div/div/a/h2"));
                driver.FindElement(By.XPath("//html/body/div/div[2]/div/ul/li[" + i + "]/div/div/a/h2")).Click();

                var expected = driver.Title;
                datarow.Newrow("Title", expected, actual, expected == actual ? "PASS" : "FAIL", driver);
                num2++;
                driver.Navigate().Back();
            }
        }
    }
}