// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using Selenium;
    using System;
    using System.Data;
    
    internal class Homepagelinks
    {
        public void HompageLinks(datarow datarow, IWebDriver driver, ISelenium selenium)
        {
            DataSet excelData = new GeneralLibrary().GetExcelData(@"C:\Selenium\Input Data\Object Repository.xls", "Modrophenia");
            driver.FindElement(By.CssSelector("img")).Click();
            selenium.WaitForPageToLoad("30000");
            decimal count = driver.FindElements(By.XPath("//html/body/div/div[2]/div/ul/li")).Count;
            int num2 = 0;
            for (int i = 1; i <= count; i++)
            {
                DataTable table = excelData.Tables[0];
                string actual = table.Rows[num2]["HomePageLinks"].ToString();
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                IWebElement element = driver.FindElement(By.XPath("//html/body/div/div[2]/div/ul/li[" + i + "]/div/div/a/h2"));
                driver.FindElement(By.XPath("//html/body/div/div[2]/div/ul/li[" + i + "]/div/div/a/h2")).Click();
                selenium.WaitForPageToLoad("30000");
                string expected = driver.Title.ToString();
                if (expected == actual)
                {
                    datarow.newrow("Title", expected, actual, "PASS", driver, selenium);
                }
                else
                {
                    datarow.newrow("Title", expected, actual, "FAIL", driver, selenium);
                }
                num2++;
                driver.Navigate().Back();
                selenium.WaitForPageToLoad("30000");
            }
        }
    }
}
