// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using Selenium;
    using System;
    
    internal class LoginRegistration
    {
        public void registration(IWebDriver driver, ISelenium selenium, datarow_TPS datarow)
        {
            MoBankUI.Screenshot screenshot = new MoBankUI.Screenshot();
            string location = selenium.GetLocation();
            try
            {
                if ((location.Contains("Login") || location.Contains("StepSelectAccountType")) || selenium.IsTextPresent("Login"))
                {
                    new LoginandRegistration_TPS().Login_TPS(driver, selenium, datarow);
                }
                else if (location.Contains("Checkout"))
                {
                    new UserData_TPS().userdata_TPS(driver, selenium, datarow);
                }
                else
                {
                    datarow.newrowTPS("Checkout Process Not covered in the Framework", "Expected", location, "FAIL", driver, selenium);
                    screenshot.screenshotfailed(driver, selenium);
                }
            }
            catch (Exception exception)
            {
                string actual = exception.ToString();
                datarow.newrowTPS("Exception", "Not Expected", actual, "FAIL", driver, selenium);
                screenshot.screenshotfailed(driver, selenium);
            }
        }
    }
}
