// Generated by .NET Reflector from C:\Program Files\Default Company Name\Selenium Test Tool\MoBankUI.exe
namespace MoBankUI
{
    using OpenQA.Selenium;
    using Selenium;
    using System;
    
    public class MoShopConsole
    {
        private MoBankUI.datarow datarow = new MoBankUI.datarow();
        private MoBankUI.Screenshot screenshot = new MoBankUI.Screenshot();
        
        public void Homepagetabs(IWebDriver driver, ISelenium selenium)
        {
            try
            {
                Exception exception;
                this.datarow.col();
                string actual = driver.Title.ToString();
                if (actual == "Log On : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("MoshopTitle", "Log On : mobank.co.uk/MoShop", actual, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("MoshopTitle", "Log On : mobank.co.uk/MoShop", actual, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.Id("Email")).Clear();
                driver.FindElement(By.Id("Email")).SendKeys("teja.vellanki@mobankgroup.com");
                driver.FindElement(By.Id("Password")).Clear();
                driver.FindElement(By.Id("Password")).SendKeys("Apple12345");
                driver.FindElement(By.Id("LogOn_Action_LogOn")).Click();
                driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10.0));
                IWebElement element = driver.FindElement(By.XPath("//div[@id='IndexMenu']/ul/li/ul/li/a"));
                string str2 = driver.Title.ToString();
                if (str2 == "mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("MoshopHomepageTitle", "mobank.co.uk/MoShop", str2, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("MoshopHomepageTitle", "mobank.co.uk/MoShop", str2, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.XPath("//div[@id='IndexMenu']/ul/li/ul/li/a")).Click();
                string str3 = driver.Title.ToString();
                if (str3 == "Scrapes : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Scrape Page", "Scrapes : mobank.co.uk/MoShop", str3, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Scrape Page", "Scrapes : mobank.co.uk/MoShop", str3, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Shops')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                string str4 = driver.Title.ToString();
                if (str4 == "Shops : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Shops Page", "Scrapes : mobank.co.uk/MoShop", str4, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Shops Page", "Scrapes : mobank.co.uk/MoShop", str4, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Global Customisations')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                string str5 = driver.Title.ToString();
                if (str5 == "Global Customisations : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Global Customerisations Page", "Global Customisations : mobank.co.uk/MoShop", str5, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Global Customerisations Page", "Global Customisations : mobank.co.uk/MoShop", str5, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Transformations')])[2]")).Click();
                string str6 = driver.Title.ToString();
                if (str6 == "Transformations : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Transformations Page", "Transformations : mobank.co.uk/MoShop", str6, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Transformations Page", "Transformations : mobank.co.uk/MoShop", str6, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Global Settings')])[2]")).Click();
                string str7 = driver.Title.ToString();
                if (str7 == "mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Global settings Page", "mobank.co.uk/MoShop", str7, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Global settings Page", "mobank.co.uk/MoShop", str7, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Security')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                string str8 = driver.Title.ToString();
                if (str8 == "mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Security Page", "mobank.co.uk/MoShop", str8, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Security Page", "mobank.co.uk/MoShop", str8, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.CssSelector("#IndexMenu > ul > li > a")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Security')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Groups')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                driver.FindElement(By.XPath("(//a[contains(text(),'Teja Vellanki')])[2]")).Click();
                selenium.WaitForPageToLoad("30000");
                string str9 = driver.Title.ToString();
                if (str9 == "Teja Vellanki : mobank.co.uk/MoShop")
                {
                    this.datarow.newrow("Account Page", "Teja Vellanki : mobank.co.uk/MoShop", str9, "PASS", driver, selenium);
                }
                else
                {
                    this.datarow.newrow("Account Page", "Teja Vellanki : mobank.co.uk/MoShop", str9, "FAIL", driver, selenium);
                    this.screenshot.screenshotfailed(driver, selenium);
                }
                driver.FindElement(By.LinkText("MoShop")).Click();
                selenium.WaitForPageToLoad("30000");
                try
                {
                    new LookandFeel().lookandfeel(driver, selenium, this.datarow);
                }
                catch (Exception exception1)
                {
                    exception = exception1;
                }
                this.datarow.newrow("", "", "Scarpe Configuration", "", driver, selenium);
                try
                {
                    new Createscrape().createscrape(driver, selenium, this.datarow);
                }
                catch (Exception exception2)
                {
                    exception = exception2;
                }
            }
            catch (Exception exception3)
            {
                string str10 = exception3.ToString();
                this.datarow.newrow("Exception", "Exception Not Expected", str10, "FAIL", driver, selenium);
            }
            finally
            {
                this.datarow.excelsave("MoshopConsole", driver, selenium);
                this.screenshot.screenshotfailed(driver, selenium);
                driver.Quit();
            }
        }
        
        private bool IsElementPresent(By by, IWebDriver driver)
        {
            try
            {
                driver.FindElement(by);
                return true;
            }
            catch (NoSuchElementException)
            {
                return false;
            }
        }
    }
}
